### ISSUE TITLE
How to resolve this error : tty already in use

### ISSUE THREAD

**Issue by cmoulliard** [openshift/installer#1616] opened 2019-04-13 09:19 UTC
## Issue

During the creation of an OCP4 on a Centos7 VM running on Virtualbox where libvirt is running, I'm getting this error when the openshift-installer command is issued toward the `qemu+tcp://192.168.99.50/system` running within the Virtualbox VM

```
ERROR *** libvirt_network.net: Error defining libvirt network: virError(Code=1, Domain=19, Message='internal error: bridge name 'tt0' already in use.') -   <network>
```

## Full stack
```
../bin/openshift-install create cluster
? SSH Public Key /Users/dabou/.ssh/id_rsa.pub
? Platform libvirt
? Libvirt Connection URI qemu+tcp://192.168.99.50/system
? Base Domain dabou.io
? Cluster Name snowdrop
? Pull Secret [? for help] ******************************************************************************************************************************************************************************INFO Fetching OS image: rhcos-410.8.20190325.0-qemu.qcow2 ***********************************************************************************************************************************************INFO Creating infrastructure resources...         *******************************************************************************************************************************************************ERROR                                              ******************************************************************************************************************************************************ERROR Error: Error applying plan:                  ******************************************************************************************************************************************************ERROR                                              ******************************************************************************************************************************************************ERROR 1 error occurred:                            ******************************************************************************************************************************************************ERROR *** libvirt_network.net: 1 error occurred:    *****************************************************************************************************************************************************ERROR *** libvirt_network.net: Error defining libvirt network: virError(Code=1, Domain=19, Message='internal error: bridge name 'tt0' already in use.') -   <network> ***********************************ERROR       <name>snowdrop-xdpzj</name>            ******************************************************************************************************************************************************ERROR       <forward mode="nat"></forward>         ******************************************************************************************************************************************************ERROR       <bridge name="tt0" stp="on"></bridge>  ******************************************************************************************************************************************************ERROR       <domain name="snowdrop.dabou.io" localOnly="yes"></domain> **********************************************************************************************************************************ERROR       <dns>                                  *************************************************************************************************
ERROR           <host ip="192.168.126.10">
ERROR               <hostname>api.snowdrop.dabou.io</hostname>
ERROR           </host>
ERROR           <host ip="192.168.126.11">
ERROR               <hostname>api.snowdrop.dabou.io</hostname>
ERROR               <hostname>etcd-0.snowdrop.dabou.io</hostname>
ERROR           </host>
ERROR           <srv service="etcd-server-ssl" protocol="tcp" target="etcd-0.snowdrop.dabou.io" port="2380" weight="10" domain="snowdrop.dabou.io"></srv>
ERROR       </dns>
ERROR       <ip address="192.168.126.1" family="ipv4" prefix="24"></ip>
ERROR   </network>
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR Terraform does not automatically rollback in the face of errors.
ERROR Instead, your Terraform state file has been partially updated with
ERROR any resources that successfully completed. Please address the error
ERROR above and apply again to incrementally change your infrastructure.
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
```

### Version

openshift-install version
openshift-install v0.16.1
built from commit e3fceacc975953f56cb09931e6be015a36eb6075

**Comment by TristanCacqueray** [comment] 2019-04-19 06:22
It seems like a duplicate of https://github.com/openshift/installer/issues/707 .
Running "./scripts/maintenance/virsh-cleanup.sh" should fix this.

**Comment by wking** [comment] 2019-04-23 23:55
Agreed, dup of #707.

/close

**Closed by wking** 2019-04-23 23:55 UTC
