### ISSUE TITLE
Stuck in waiting for bootstrap to complete although bootstrap has completed

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [openshift/installer#3387] opened 2020-03-31 14:04 UTC
#2640 Version

```console
$ openshift-install version
openshift-install v4.3.5
built from commit 82f9a63c06956b3700a69475fbd14521e139aa1e
release image quay.io/openshift-release-dev/ocp-release@sha256:64320fbf95d968fc6b9863581a92d373bc75f563a13ae1c727af37450579f61a
```

# Platform:
UPI on openstack

# What happened?

While trying to deploy openshift via installer on openstack using UPI i ran into this bug. After running `openshift-install wait-for bootstrap-complete` it gets stuck there forever: 

```
INFO Waiting up to 30m0s for bootstrapping to complete...
```
Although, from `bootkube.service` logs i can see that the bootstrap has already completed. If i stop and re-run the command it passes this stage.

# What you expected to happen?

For the installer to move forward as soon as the corresponding signal is sent

**Comment by abhinavdahiya** [comment] 2020-03-31 20:32
It is quite possible that the LB being used in this setup is not sending RST when the backend _bootstrap-host_ turns off the service.

/assign @mandre @Fedosin 
/label platform/openstack

**Comment by mandre** [comment] 2020-05-14 14:59
Closing as a duplicate of https://github.com/openshift/installer/issues/3410

Please re-open if this isn't the case and you're still seing the error.

/close

**Closed** 2020-05-14 14:59 UTC
Labels: platform/openstack
