### ISSUE TITLE
VM deployment failed through terraform during OpenShift deployment

### ISSUE THREAD

**Issue by arunabhabanerjee** [openshift/installer#2785] opened 2019-12-10 21:08 UTC
# Version

```console
$ openshift-install version
<openshift-install v4.2.8
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image quay.io/openshift-release-dev/ocp-release@sha256:4bf307b98beba4d42da3316464013eac120c6e5a398646863ef92b0e2c621230>
```

# Platform:

# What happened?

Unable to deploy VM through Terraform.

# What you expected to happen?

Terraform should able to deploy VM

# How to reproduce it (as minimally and precisely as possible)?

Install terraform v0.12.17 and run terraform apply -auto-approve

root:/home/arunabha/vsphere>terraform apply -auto-approve
module.control_plane.data.ignition_systemd_unit.restart[0]: Refreshing state...
module.control_plane.data.ignition_file.hostname[0]: Refreshing state...
module.control_plane.data.ignition_file.hostname[1]: Refreshing state...
module.control_plane.data.ignition_systemd_unit.restart[1]: Refreshing state...
module.compute.data.ignition_file.hostname[0]: Refreshing state...
module.bootstrap.data.ignition_file.hostname[0]: Refreshing state...
module.bootstrap.data.ignition_systemd_unit.restart[0]: Refreshing state...
module.control_plane.data.ignition_systemd_unit.restart[2]: Refreshing state...
module.compute.data.ignition_systemd_unit.restart[1]: Refreshing state...
module.compute.data.ignition_systemd_unit.restart[2]: Refreshing state...
module.compute.data.ignition_file.hostname[1]: Refreshing state...
module.control_plane.data.ignition_file.hostname[2]: Refreshing state...
module.compute.data.ignition_file.hostname[2]: Refreshing state...
module.compute.data.ignition_systemd_unit.restart[0]: Refreshing state...
data.vsphere_datacenter.dc: Refreshing state...
module.bootstrap.data.vsphere_network.network: Refreshing state...
module.bootstrap.data.vsphere_datastore.datastore: Refreshing state...
module.control_plane.data.vsphere_virtual_machine.template: Refreshing state...
module.bootstrap.data.vsphere_virtual_machine.template: Refreshing state...
module.resource_pool.data.vsphere_compute_cluster.compute_cluster: Refreshing state...
module.compute.data.vsphere_datastore.datastore: Refreshing state...
module.control_plane.data.vsphere_datastore.datastore: Refreshing state...
module.control_plane.data.vsphere_network.network: Refreshing state...
module.compute.data.vsphere_network.network: Refreshing state...
module.compute.data.vsphere_virtual_machine.template: Refreshing state...

Error: Invalid template interpolation value

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  28:
  29:
  30:
  31:
  32:
  33:
  34: IPADDR="${local.ip_addresses[count.index]}"
  35:
  36:
  37:
  38:
  39:
    |----------------
    | count.index is 0
    | local.ip_addresses is tuple with 1 element

Cannot include the given value in a string template: string required.

Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR="${local.ip_addresses[count.index]}"
    |----------------
    | count.index is 2
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.

Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR="${local.ip_addresses[count.index]}"
    |----------------
    | count.index is 1
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.

Error: Invalid template interpolation value

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  28:
  29:
  30:
  31:
  32:
  33:
  34: IPADDR="${local.ip_addresses[count.index]}"
  35:
  36:
  37:
  38:
  39:
    |----------------
    | count.index is 0
    | local.ip_addresses is tuple with 1 element

Cannot include the given value in a string template: string required.

Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR="${local.ip_addresses[count.index]}"
    |----------------
    | count.index is 1
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.

Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR="${local.ip_addresses[count.index]}"
    |----------------
    | count.index is 2
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.

Error: Invalid template interpolation value

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  28:
  29:
  30:
  31:
  32:
  33:
  34: IPADDR="${local.ip_addresses[count.index]}"
  35:
  36:
  37:
  38:
  39:
    |----------------
    | count.index is 0
    | local.ip_addresses is tuple with 1 element

Cannot include the given value in a string template: string required.

**Comment by abhinavdahiya** [comment] 2019-12-10 23:02
duplicate of https://github.com/openshift/installer/issues/2183

/close

**Closed by abhinavdahiya** 2019-12-10 23:02 UTC
