### ISSUE TITLE
Any way to config `--pod-infra-container-image` for kubelet ?

### ISSUE THREAD

**Issue by cospotato** [openshift/installer#3695] opened 2020-06-01 07:28 UTC
# Version

```console
$ openshift-install version
openshift-install 4.4.0-0.okd-2020-05-23-055148-beta5
built from commit 0f0142e7261349b93c3dd3dd02a9ce164dfd2d4f
release image quay.io/openshift/okd@sha256:057e2eead0443a60877fc9b579770e6464eb7fa8d92855f5c2f09ef7340d60db
```

# Platform:

VMWare

# What happened?

I found that `/usr/local/bin/crio-configure.sh` configed `pause_image` in `crio.conf`

```conf
# The image used to instantiate infra containers.
# This option supports live configuration reload.
pause_image = "quay.io/openshift/okd-content@sha256:6e848b9eb42cd4a009b3f02518b3699cbc12d5f84fa2737084c7b73df4f5f5af"
```

But i got these error in `kubelet` log

```console
6月 01 07:21:26 bootstrap hyperkube[1109]: E0601 07:21:26.911764    1109 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-bootstrap-member-bootstrap_openshift-etcd_05d8e8b5962cbd87ac086bd1beb9bd65_0": Error initializing source docker://k8s.gcr.io/pause:3.1: error pinging docker registry k8s.gcr.io: Get https://k8s.gcr.io/v2/: dial tcp 74.125.23.82:443: i/o timeout
6月 01 07:21:26 bootstrap hyperkube[1109]: E0601 07:21:26.912531    1109 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "etcd-bootstrap-member-bootstrap_openshift-etcd(05d8e8b5962cbd87ac086bd1beb9bd65)" failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-bootstrap-member-bootstrap_openshift-etcd_05d8e8b5962cbd87ac086bd1beb9bd65_0": Error initializing source docker://k8s.gcr.io/pause:3.1: error pinging docker registry k8s.gcr.io: Get https://k8s.gcr.io/v2/: dial tcp 74.125.23.82:443: i/o timeout
6月 01 07:21:26 bootstrap hyperkube[1109]: E0601 07:21:26.912598    1109 kuberuntime_manager.go:729] createPodSandbox for pod "etcd-bootstrap-member-bootstrap_openshift-etcd(05d8e8b5962cbd87ac086bd1beb9bd65)" failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-bootstrap-member-bootstrap_openshift-etcd_05d8e8b5962cbd87ac086bd1beb9bd65_0": Error initializing source docker://k8s.gcr.io/pause:3.1: error pinging docker registry k8s.gcr.io: Get https://k8s.gcr.io/v2/: dial tcp 74.125.23.82:443: i/o timeout
6月 01 07:21:26 bootstrap hyperkube[1109]: E0601 07:21:26.912762    1109 pod_workers.go:191] Error syncing pod 05d8e8b5962cbd87ac086bd1beb9bd65 ("etcd-bootstrap-member-bootstrap_openshift-etcd(05d8e8b5962cbd87ac086bd1beb9bd65)"), skipping: failed to "CreatePodSandbox" for "etcd-bootstrap-member-bootstrap_openshift-etcd(05d8e8b5962cbd87ac086bd1beb9bd65)" with CreatePodSandboxError: "CreatePodSandbox for pod \"etcd-bootstrap-member-bootstrap_openshift-etcd(05d8e8b5962cbd87ac086bd1beb9bd65)\" failed: rpc error: code = Unknown desc = error creating pod sandbox with name \"k8s_etcd-bootstrap-member-bootstrap_openshift-etcd_05d8e8b5962cbd87ac086bd1beb9bd65_0\": Error initializing source docker://k8s.gcr.io/pause:3.1: error pinging docker registry k8s.gcr.io: Get https://k8s.gcr.io/v2/: dial tcp 74.125.23.82:443: i/o timeout"
```

`kubelet` still using `k8s.gcr.io/pause:3.1` as default infra image

```console
$ /usr/bin/hyperkube kubelet --help | grep gcr
      --pod-infra-container-image string                                                                          The image whose network/ipc namespaces containers in each pod will use. This docker-specific flag only works when container-runtime is set to docker. (default "k8s.gcr.io/pause:3.1")
```

# What you expected to happen?

Let `kubelet` using infra image in `crio.conf` or provide some way to define the infra-image for `kubelet`

# How to reproduce it (as minimally and precisely as possible)?

As above

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by vrutkovs** [comment] 2020-06-12 07:30
Dupe of https://github.com/openshift/okd/issues/187

/close

**Closed** 2020-06-12 07:30 UTC
