### ISSUE TITLE
Cannot access console

### ISSUE THREAD

**Issue by eivantsov** [openshift/installer#1145] opened 2019-01-29 18:26 UTC
# Version

```console
eugene@ivantsoft ~/go/src/github.com/openshift/fourdotoh $ ../installer/bin/openshift-install version
../installer/bin/openshift-install v0.9.1

```

# Platform 

libvirt
# What happened?
The installation was a success. However, I cannot access `https://console-openshift-console.apps.ivantsoft.tt.testing` with cannot resolve host error:

```
INFO Fetching OS image: redhat-coreos-maipo-47.249-qemu.qcow2.gz 
INFO Creating cluster...                          
INFO Waiting up to 30m0s for the Kubernetes API... 
INFO API v1.11.0+0583818 up                       
INFO Waiting up to 30m0s for the bootstrap-complete event... 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 10m0s for the openshift-console route to be created... 
INFO Install complete!                            
INFO Run 'export KUBECONFIG=/home/eugene/go/src/github.com/openshift/fourdotoh/auth/kubeconfig' to manage the cluster with 'oc', the OpenShift CLI. 
INFO The cluster is ready when 'oc login -u kubeadmin -p agKe6-iiqN7-iuaQw-hP6ru' succeeds (wait a few minutes). 
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.ivantsoft.tt.testing 
INFO Login to the console with user: kubeadmin, password: agKe6-iiqN7-iuaQw-hP6ru 
```
Did I miss a configuration step? I can access API without any issues though

It looks like https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md#set-up-networkmanager-dns-overlay did not work for me and an internal dns isn't resolved.

**Comment by abhinavdahiya** [comment] 2019-01-29 20:23
/close

duplicate of https://github.com/openshift/installer/issues/1007

**Closed by abhinavdahiya** 2019-01-29 20:23 UTC
