### ISSUE TITLE
[AWS]wildcard entry not getting created in route53

### ISSUE THREAD

**Issue by DirectedSoul1** [openshift/installer#1051] opened 2019-01-11 18:47 UTC
# Version

```console
$ openshift-install version
v0.9.1
```

# Platform (aws|libvirt|openstack):

AWS

# What happened?

- Master and worker nodes are up and running
- Not getting any info on url for loggin in
- Wildcard entry is not getting generated on private zone in route53
hitting below message after instances comes up 

``` 
level=info msg="Waiting up to 10m0s for the openshift-console route to be created..."
level=fatal msg="waiting for openshift-console URL: context deadline exceeded"
```

# What you expected to happen?

Expected to create a wildcard entry in route53
```*.apps.<cluster-id>``` entry was supposed to be generated during the install process 

# How to reproduce it (as minimally and precisely as possible)?

Pull the latest bits from the github
follow the steps mentioned as below 
reference link:
https://github.com/openshift/installer/tree/master
Quick Start
First, install all build dependencies.

Clone this repository to src/github.com/openshift/installer in your GOPATH. Then build the openshift-install binary with:

hack/build.sh
This will create bin/openshift-install. This binary can then be invoked to create an OpenShift cluster, like so:

bin/openshift-install create cluster
The installer will show a series of prompts for user-specific information and use reasonable defaults for everything else. In non-interactive contexts, prompts can be bypassed by providing an install-config.yaml.

If you have trouble, refer to the troubleshooting guide.

# References

might be closely related to 
https://github.com/openshift/cluster-ingress-operator/pull/99

**Comment by wking** [comment] 2019-01-11 19:05
> might be closely related to openshift/cluster-ingress-operator#99

Can you try with an update payload that includes that change?  Otherwise, maybe do some [generic troubleshooting][1]?

/label platform/aws

[1]: https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#generic-troubleshooting

**Comment by DirectedSoul1** [comment] 2019-01-11 19:11
sure, ill try with the new payload and get back asap.

**Comment by DTMad** [comment] 2019-01-17 08:45
I can reproduce this with installer version 0.10.0
There seems to be a bug within the installer.

Where should the wildcard entry point to?
Is there a workaround until the bug is fixed?

**Comment by crawford** [comment] 2019-01-17 23:11
@DTMad the installer doesn't create this entry. It is created by the ingress operator. The installer releases pin to a specific release image, which contains particular versions of every operator. We'll have to wait for the fix to the ingress operator before we can release a new installer.

**Comment by wking** [comment] 2019-01-18 01:14
This may be the same as https://bugzilla.redhat.com/show_bug.cgi?id=1666846 , in case folks make progress there first.

**Comment by akostadinov** [comment] 2019-01-18 08:30
openshift/cluster-ingress-operator#99 is merged

**Comment by wking** [comment] 2019-01-18 08:40
> openshift/cluster-ingress-operator#99 is merged

Unfortunately it appears to not have fixed this, at least for all cases.  It was part of the update payload pinned by installer 0.10.0:

```console
$ oc adm release info --pullspecs quay.io/openshift-release-dev/ocp-release:4.0.0-0.1 | grep ingress
  cluster-ingress-operator                      quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:be0a6d7f9e585aa534ee9cdc02fd485e6eaf88b05137c5554098cce163a50e18
$ oc image info quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:be0a6d7f9e585aa534ee9cdc02fd485e6eaf88b05137c5554098cce163a50e18 | grep commit-url
             io.openshift.source-commit-url=https://github.com/openshift/cluster-ingress-operator/commit/d833c55c22223850a15fd1f5e884be5d93da3ec6
$ git log --graph --oneline --decorate -11 d833c55
*   d833c55 Merge pull request #94 from ramr/ne-72.1
|\  
| * e8ebfaf (origin/pr/94) Fix uid issue - need to return current/actual asset in case of deployment.
| * e11f8f5 Add perms to allow updates to namespaces.
| * 8d6461c [NE-72] Handle updates to ClusterIngress and update a subset of the 	generated ingress assets (namespace and deployment).         Includes changes as per @Miciah's and Ravi's review comments.
* |   892dd77 Merge pull request #101 from Miciah/use-cluster-infrastructure-config
|\ \  
| * | 51f0472 (origin/pr/101) Use cluster infrastructure config
| * | 7fafdc0 Update openshift/api dependency
|/ /  
* |   d7b1f14 Merge pull request #100 from Miciah/improve-error-handling-in-private-zone-discovery
|\ \  
| * | eea402f (origin/pr/100) Improve error handling in private zone discovery
|/ /  
* |   8048ea7 Merge pull request #99 from Miciah/cope-with-pagination-in-private-zone-discovery
|\ \  
| |/  
|/|   
| * 2526a4c (origin/pr/99) Cope with pagination in private zone discovery
|/  
```

And [0.10.0 seems to still have the issue][1].  So we could probably close this in favor of an ingress issue, but I don't think we can close it without replacement yet. 

[1]: https://github.com/openshift/installer/issues/1051#issuecomment-455089314

**Comment by abhinavdahiya** [comment] 2019-04-12 05:11
This should be fixed in latest installer.

/close

**Closed by abhinavdahiya** 2019-04-12 05:11 UTC
Labels: kind/bug, platform/aws
