### ISSUE TITLE
Allow force installing to replace or overwrite existing resources

### ISSUE THREAD

**Issue by soltysh** [openshift/installer#1174] opened 2019-02-01 11:39 UTC
# Version
```console
$ openshift-install version
unreleased-master-191-g810b13a90e881b87935d86fc4b84f25daa6e2516
```

# Platform (aws|libvirt|openstack):
aws

# What happened?
I was installing cluster and stumbled upon the following error message:

```
 2 errors occurred:                           
ERROR 	* module.masters.aws_iam_instance_profile.master: 1 error occurred: 
ERROR 	* aws_iam_instance_profile.master: Error creating IAM instance profile maszulik-master-profile: EntityAlreadyExists: Instance Profile maszulik-master-profile already exists. 
ERROR 	status code: 409, request id: 4ef868f7-2612-11e9-9385-61fa1054d42b 
```

which prevents me from processing further. I need to either switch to other region or :man_shrugging: 

# What you expected to happen?
I'd like to be able to force install so that the existing resources will get overridden by the new installation. 

# How to reproduce it (as minimally and precisely as possible)?
In my case it was I left the cluster up and running last week and that go automatically cleaned during the weekend. Now, I'm struggling with the described situation, but I don't think that's easily reproducible. 

/cc @tnozicka who also experienced similar issues last week

**Comment by tnozicka** [comment] 2019-02-01 11:48
I have encountered the same thing, got more errors but including this one as well. Generally the issue is the installer tells me the same resources already exist and it fails on that. Might be they didn't got cleaned up on destroy or I didn't run it a month ago, doesn't really matter - installer should be able to replace those with flag `--overwrite` or `--force`.

Heard it from another guy as well - the unfortunate solution seems to be changing cluster names / regions which you run out of soon.

**Comment by soltysh** [comment] 2019-02-01 12:04
> the unfortunate solution seems to be changing cluster names / regions which you run out of soon.

That didn't work for me, just tried :sob:

**Comment by wking** [comment] 2019-02-01 16:54
Lots more chit-chat [here][1] if you want short-term debugging.  Mid-term, #762 will solve "new clusters collide with existing clusters".  But you'll want to reliably run `destroy cluster` to avoid leaking cruft, regardless.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1669274

**Comment by tnozicka** [comment] 2019-02-04 17:01
`But you'll want to reliably run destroy cluster to avoid leaking cruft, regardless.`

Relaying on a person to *ALWAYS* destroy his cluster is a faulty assumption. People do mistakes. e.g. running this in the installer dir and doing `git clean -xfd` or using tmpdir or just accidentally deleting it are common things in dev env, that's why it's not a production and people do mistakes also there. If you intend to keep such important info in local file system you have to account for a path when it is lost. Not even talking about working from more then one laptop.

Implementing `--overwrite` would seem to account for those cases.

**Comment by wking** [comment] 2019-02-04 19:31
> Relying on a person to ALWAYS destroy his cluster is a faulty assumption.

#746 has some more discussion on this, and serious accounts will want some way to backstop leaked resources (openshift-dev uses [this script][1]).  And again, once we address #762, leaked resources won't block new clusters (and an installer `--overwrite` would end up as useless cruft).  The backstops protect you from forgetful users, so you need them, but proactively calling `destroy cluster` saves you money and helps keep the account under its limits by removing unused resources before the backstops gets to them.

[1]: https://github.com/openshift/li/blob/f45a7bbec611f88c48b0c2d92e124257f09b2cd5/tools/src/aws/aws_resource_manager.py

**Comment by eparis** [comment] 2019-02-18 18:45
Anyone who has instance profiles they need to delete. Do it by hand for example:
`aws --region=eu-west-2 iam delete-instance-profile --instance-profile-name eparis1-worker-profile`

This (almost certainly) happened because you left your cluster running for 48h in openshift-dev instead of cleaning it up like you should have. Please feel free to comment in the DPP ticket that their cleanup affected you.

https://jira.coreos.com/browse/DPP-1130

**Comment by eparis** [comment] 2019-02-20 21:01
I'm going to close this issue. I do not believe we should implement a --overwrite feature.

https://github.com/openshift/installer/pull/1268
should allow destroy cluster to work even after the DPP scripts have cleaned things up partially. Until then you'll have to clean up by hand.

**Closed by eparis** 2019-02-20 21:01 UTC
