### ISSUE TITLE
Support for AzureGov "https://management.core.usgovcloudapi.net/" API endpoint

### ISSUE THREAD

**Issue by bit4man** [openshift/installer#3099] opened 2020-02-12 16:14 UTC
```$ openshift-install version
openshift-install v4.3.0
built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e
release image quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d
```
Platform: AzureGov

After entering keys when running openshift-install create install-config the follow error is returned when the installer tries to query for the DNS zones available:

```FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": failed to get list of regions: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxxxxxxx/locations?api-version=2016-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request.```

**Comment by abhinavdahiya** [comment] 2020-02-12 17:15
duplicate of https://github.com/openshift/installer/issues/2775

/close

**Closed by abhinavdahiya** 2020-02-12 17:15 UTC
