### ISSUE TITLE
[Openstack] After cluster reboot all nodes in NotReady state

### ISSUE THREAD

**Issue by MartijnStraatman** [openshift/installer#2344] opened 2019-09-11 19:49 UTC
# Version

```console
built from commit 2324f2f4e1f2b819d68a4f3bdcc8ef23bcdbd37d
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:
Openstack 14

# What happened? 

I just rebooted all the nodes (masters and workers). Afterwards all nodes are in not ready state

logs from one of the workers:
```
elet.go:2254] node "os-test-9fxbk-worker-s5fll" not found
belet.go:2254] node "os-test-9fxbk-worker-s5fll" not found
flector.go:161] Listing and watching *v1.Pod from k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47
flector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:anonymous" cannot list resource "pods" in API group "" at the cluster scope
belet.go:2254] node "os-test-9fxbk-worker-s5fll" not found
```

# What you expected to happen?

Running nodes

# How to reproduce it (as minimally and precisely as possible)?

Select all nodes in the Horizon-gui en perform a shutdown, the a reboot.

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by jiangytcn** [comment] 2019-11-13 15:16
same issue here

**Comment by pierreprinetti** [comment] 2019-12-20 11:03
Thanks for reporting, this issue is being investigated.

**Comment by mandre** [comment] 2020-01-16 15:42
We believe this is fixed with latest 4.3 nightlies. Could you give it a try and report back?

**Comment by pierreprinetti** [comment] 2020-01-23 11:03
/close

Closing for inactivity. Please reopen if the problem is still happening.

**Closed by pierreprinetti** 2020-01-23 11:03 UTC
Labels: platform/openstack

**Comment by MartijnStraatman** [comment] 2020-01-23 12:55
confirmed working afer reboot
