### ISSUE TITLE
Openshift 4.4.4 Terraform installer

### ISSUE THREAD

**Issue by dbarreda** [openshift/installer#3680] opened 2020-05-28 19:24 UTC
# Version

```console
$ terraform version
Terraform v0.11.15-oci

Last time I tried newer version the installer was broken, not sure if this has changed since 4.1.
```

# Platform:
vSphere

# What happened?

Cloned the repository. Terraform init wont run.
vsphere zzz$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /Users/zzz/k8s1/installer/upi/vsphere/main.tf: At 4:25: Unknown token: 4:25 IDENT formatlist

# What you expected to happen?

To continue the process to move on with the installation

# How to reproduce it (as minimally and precisely as possible)?

git clone https://github.com/openshift/installer.git
cd installer/upi/vsphere/
cp terraform.tfvars.example terraform.tfvars
modify the file with actual values
terraform init

```console
$ git clone https://github.com/openshift/installer.git
$ cd installer/upi/vsphere/
$ cp terraform.tfvars.example terraform.tfvars
$ modify the file with actual values
$ terraform init
```

# Anything else we need to know?

I don't think so.

**Comment by abhinavdahiya** [comment] 2020-05-28 19:32
duplicate of https://github.com/openshift/installer/issues/3629

/close

**Closed** 2020-05-28 19:32 UTC
