### ISSUE TITLE
Installer does not use AWS profile 

### ISSUE THREAD

**Issue by zopechetan** [openshift/installer#2348] opened 2019-09-12 18:14 UTC
# Version

```console
$ openshift-install version
./openshift-install v4.1.15-201909041605-dirty
built from commit 7f73283bde29386b43b9300208a39243cca41b15
release image quay.io/openshift-release-dev/ocp-release@sha256:0a7f743a98e4d0937f44561138a03db8c09cdc4817a771a67f154e032435bcef
```

# Platform:

AWS
# What happened?
We are using aws federated account . I need to install openshift in a shared account which I am accessing by assuming role from a different(federated)  aws account. I can access Shared account only by using credentials of individual federated account.

Files under .aws directory :

config.sh
[profile SharedAccount]
role_arn = arn:aws:iam::###########:role/EC2Role
source_profile = XYZ
region = us-east-2
output = json 

credentials.sh 
[XYZ]
aws_access_key_id     = ###################
aws_secret_access_key = #######################

Normal aws commands run fine by this : eg:  aws ec2 describe-instances --profile SharedAccount

Even after setting the AWS_PROFILE env var  , openshift installer asks for aws_access and aws_secret keys and is not able to access the SharedAccount on which I need to install.

Even after providing access and secret it just appends the credentials file and still accesses federated account and not the shared account.
I dont have permissions to create resources in federated account and everything needs to be created in SharedAccount  by switching/assuming role.

# What you expected to happen?

Should have assumed the role and accessed the SharedAccount to create required resources.

# How to reproduce it (as minimally and precisely as possible)?
Configure aws cli as shown above and run the openshift installer with SharedAccount profile set.

```console
openshift]$ export AWS_PROFILE=SharedAccount
[ec2-user@ip-172-31-22-10 openshift]$ ./openshift-install --dir=openshift_install/ create cluster

```

# Anything else we need to know?

Enter text here.

# References

According to this : https://docs.openshift.com/containerplatform/4.1/installing/installing_aws/installing-aws-default.html

If you do not have an Amazon Web Services (AWS) profile stored on your computer, enter the AWS access key ID and secret access key for the user that you configured to run the installation program.

**Comment by zopechetan** [comment] 2019-09-13 13:19
[ec2-user@ip-172-31-22-10 .aws]$ cat config
[profile SharedAccount]
role_arn = arn:aws:iam::#############:role/EC2Role
source_profile = TIBCO
region = us-east-2
output = json
[ec2-user@ip-172-31-22-10 .aws]$ cat credentials
[TIBCO]
aws_access_key_id     = ######################
aws_secret_access_key = #######################

[ec2-user@ip-172-31-22-10 .aws]$ cd /home/ec2-user/openshift/
[ec2-user@ip-172-31-22-10 openshift]$ export AWS_PROFILE=SharedAccount
[ec2-user@ip-172-31-22-10 openshift]$ ./openshift-install --dir=openshift_install/ create cluster
? Platform aws
? AWS Access Key ID ##########################
? AWS Secret Access Key [? for help] ****************************************
INFO Writing AWS credentials to "/home/ec2-user/.aws/credentials" (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)
? Region us-east-2
FATAL failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to fetch dependency of "Cluster ID": failed to fetch dependency of "Install Config": failed to generate asset "Base Domain": no public Route 53 hosted zones found

[ec2-user@ip-172-31-22-10 openshift]$ aws route53 get-hosted-zone --id Z3A9E72YAIEKI6
{
    "HostedZone": {
        "ResourceRecordSetCount": 2,
        "CallerReference": "96BDA7C9-88DD-2197-880B-43EA761E6E08",
        "Config": {
            "Comment": "Hosted zone for openshift",
            "PrivateZone": false
        },
        "Id": "/hostedzone/Z3A9E72YAIEKI6",
        "Name": "openshift.tibcopcf.net."
    },
    "DelegationSet": {
        "NameServers": [
            "ns-640.awsdns-16.net",
            "ns-1126.awsdns-12.org",
            "ns-322.awsdns-40.com",
            "ns-2043.awsdns-63.co.uk"
        ]
    }
}


The sub-domain is present ..but installer is not able to find it as it is looking into the individual account and not the SharedAccount . After setting the aws profile , I can successfully execute the aws cli commands on SharedAccount as shown above.

**Comment by abhinavdahiya** [comment] 2019-11-05 20:25
duplicate of https://github.com/openshift/installer/issues/1535

**Comment by abhinavdahiya** [comment] 2020-02-11 21:03
> duplicate of #1535

/close

**Closed by abhinavdahiya** 2020-02-11 21:03 UTC
