### ISSUE TITLE
Libvirt installation fails - stuck on master node vm

### ISSUE THREAD

**Issue by mmirecki** [openshift/installer#2717] opened 2019-11-25 15:02 UTC
# Version
Tried with multiple 4.3 versions:

```console
$ openshift-install version
# built from lastest master:
./openshift-install unreleased-master-2182-g8e75675f373d7ca46ec7fa4b4156ce75287735d1
built from commit 8e75675f373d7ca46ec7fa4b4156ce75287735d1
release image registry.svc.ci.openshift.org/origin/release:4.3
```
downloaded from openshift-release.svc.ci.openshift.org:
```console
$ openshift-install version
# built from lastest master:
./openshift-install-libvirt unreleased-master-2104-g98dcac423d53c187726140e21ed88af69c865de1
built from commit 98dcac423d53c187726140e21ed88af69c865de1
release image registry.svc.ci.openshift.org/origin/release:4.3
```
# Platform:
libvirt

# What happened?
The installation gets stuck on the master node vm.
Only the bootstrap and master vms are created, the worker is not.
The master vm comes up reaching a stage as visible on the screenshot:
![master vm screenshot](https://user-images.githubusercontent.com/16225320/69551241-a6719d80-0f9c-11ea-8f8c-05a839daa261.png)
waits in this state for several minutes, and reboots (and repeats ...)

The log bundle for the installation:
[log-bundle-20191125120718.tar.gz](https://github.com/openshift/installer/files/3887169/log-bundle-20191125120718.tar.gz)

# How to reproduce it (as minimally and precisely as possible)?

```console
./openshift-install create cluster
```

I tried this on 2 differents envs, with different versions of openshift-installer (build manually and downloaded), with the same results.

**Comment by tucbill** [comment] 2019-11-25 22:13
I see a similar problem when I try to build openshift 4.3 cluster using libvirt on x86/RHEL7.6 server.

Looking at  bootstrap/journals/bootkube.log, I see these messages logged:
> Nov 25 18:37:26 ece1-7d99p-bootstrap podman[15402]: 2019-11-25 18:37:26.67749731 +0000 UTC m=+0.076510955 container create b51cffb4e3430b2134af7e7e671898fb17db9369b5d01738f4bd9001761469a2 (image=registry.svc.ci.openshift.org/origin/4.3-2019-11-23-155208@sha256:696a0ba7d344e625ec71d915d74d387fc2a951b879d4d54bdc69d460724c01ae, name=etcdctl)
Nov 25 18:37:27 ece1-7d99p-bootstrap podman[15402]: 2019-11-25 18:37:27.018996714 +0000 UTC m=+0.418010402 container init b51cffb4e3430b2134af7e7e671898fb17db9369b5d01738f4bd9001761469a2 (image=registry.svc.ci.openshift.org/origin/4.3-2019-11-23-155208@sha256:696a0ba7d344e625ec71d915d74d387fc2a951b879d4d54bdc69d460724c01ae, name=etcdctl)
Nov 25 18:37:27 ece1-7d99p-bootstrap podman[15402]: 2019-11-25 18:37:27.039327043 +0000 UTC m=+0.438340719 container start b51cffb4e3430b2134af7e7e671898fb17db9369b5d01738f4bd9001761469a2 (image=registry.svc.ci.openshift.org/origin/4.3-2019-11-23-155208@sha256:696a0ba7d344e625ec71d915d74d387fc2a951b879d4d54bdc69d460724c01ae, name=etcdctl)
Nov 25 18:37:27 ece1-7d99p-bootstrap podman[15402]: 2019-11-25 18:37:27.039407044 +0000 UTC m=+0.438420726 container attach b51cffb4e3430b2134af7e7e671898fb17db9369b5d01738f4bd9001761469a2 (image=registry.svc.ci.openshift.org/origin/4.3-2019-11-23-155208@sha256:696a0ba7d344e625ec71d915d74d387fc2a951b879d4d54bdc69d460724c01ae, name=etcdctl)
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: {"level":"warn","ts":"2019-11-25T18:37:32.044Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-6552bd2d-2d43-404f-ad0e-9914cfea658d/etcd-0.ece1.ece.test:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: {"level":"warn","ts":"2019-11-25T18:37:32.044Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-98ea0afb-b9c1-441e-b5b8-01628499ebc6/etcd-2.ece1.ece.test:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: {"level":"warn","ts":"2019-11-25T18:37:32.044Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-0b2dad7a-3ca4-4205-b5e2-4055831a6b3c/etcd-1.ece1.ece.test:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: https://etcd-0.ece1.ece.test:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: https://etcd-2.ece1.ece.test:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: https://etcd-1.ece1.ece.test:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: Error: unhealthy cluster
Nov 25 18:37:32 ece1-7d99p-bootstrap podman[15402]: 2019-11-25 18:37:32.073889624 +0000 UTC m=+5.472903351 container died b51cffb4e3430b2134af7e7e671898fb17db9369b5d01738f4bd9001761469a2 (image=registry.svc.ci.openshift.org/origin/4.3-2019-11-23-155208@sha256:696a0ba7d344e625ec71d915d74d387fc2a951b879d4d54bdc69d460724c01ae, name=etcdctl)
Nov 25 18:37:32 ece1-7d99p-bootstrap podman[15402]: 2019-11-25 18:37:32.168818707 +0000 UTC m=+5.567832391 container remove b51cffb4e3430b2134af7e7e671898fb17db9369b5d01738f4bd9001761469a2 (image=registry.svc.ci.openshift.org/origin/4.3-2019-11-23-155208@sha256:696a0ba7d344e625ec71d915d74d387fc2a951b879d4d54bdc69d460724c01ae, name=etcdctl)
Nov 25 18:37:32 ece1-7d99p-bootstrap bootkube.sh[2003]: etcdctl failed. Retrying in 5 seconds...

Full log bundle:
[log-bundle-20191125123818.tar.gz](https://github.com/openshift/installer/files/3888981/log-bundle-20191125123818.tar.gz)

Version information:
>  bin/openshift-install version
bin/openshift-install unreleased-master-2184-g8d9fca455e98ab2f9ab17eb34882ce874778c1d3
built from commit 8d9fca455e98ab2f9ab17eb34882ce874778c1d3
release image registry.svc.ci.openshift.org/origin/release:4.3

Note: I have successfully created both 4.2 and 4.3 clusters previouslyl but now both are failing using libvirt installer.

**Comment by abhinavdahiya** [comment] 2019-11-26 17:14
Since the problem is that RHCOS is failing to boot.. please open an issue on https://github.com/openshift/os

**Comment by jichenjc** [comment] 2019-11-28 09:19
@abhinavdahiya I suffered simliar issue ,I used to be able to create a cluster and now I am seeing following error which is weird to me , not sure it's same to @mmirecki 's root cause but symptom is very similar , wait a few minutes (enter emergency mode) then restart

looks like the ignition has some change recently? 

```
[***   ] A start job is running for Ignition (fetch) (13min 24s / no limit)[  810.714233] ignition[879]: error at line 1, column 792
[  810.714233] no filesystem specified
[  810.734772] ignition[879]: error at line 1, column 1192
[  810.734772] no filesystem specified
[  810.753585] ignition[879]: error at line 1, column 1590
[  810.753585] no filesystem specified
[  810.774830] systemd[1]: ignition-fetch.service: Main process exited, code=exited, status=1/FAILURE
[FAILED] Failed to start Ignition (fetch).
See 'systemctl s[  810.797247] ignition[879]: error at line 1, column 12194
[  810.797247] no filesystem specified
tatus ignition-fetch.service' for details.
[[  810.817983] systemd[1]: ignition-fetch.service: Failed with result 'exit-code'.
DEPEND] Dependency failed for Initrd Default Target.[  810.836679] ignition[879]: error at line 1, column 12409
[  810.836679] no filesystem specified

[  810.858315] systemd[1]: Failed to start Ignition (fetch).
[  810.858376] ignition[879]: error at line 1, column 12573
[  810.858376] no filesystem specified
[  OK  ] Started Tear dow[  810.858413] systemd[1]: Dependency failed for Initrd Default Target.
n initramfs networking.
[  810.858453] ignition[879]: error at line 1, column 12740
[  810.858453] no filesystem specified
[  810.858485] systemd[1]: initrd.target: Job initrd.target/start failed with result 'dependency'.
[  810.858537] ignition[879]: error at line 1, column 12926
[  810.858537] no filesystem specified
[  810.858570] systemd[1]: initrd.target: Triggering OnFailure= dependencies.
[  810.858608] ignition[879]: error at line 1, column 13091
[  810.858608] no filesystem specified
[  810.858642] systemd[1]: Started Tear down initramfs networking.
[  810.858678] ignition[879]: error at line 1, column 14483
[  810.858678] no filesystem specified
[  810.858708] ignition[879]: error at line 1, column 15900
[  810.858708] no filesystem specified
[  810.858737] ignition[879]: error at line 1, column 23612
[  810.858737] no filesystem specified
[  810.858766] ignition[879]: error at line 1, column 30083
[  810.858766] no filesystem specified
[  810.858795] ignition[879]: error at line 1, column 30431
[  810.858795] no filesystem specified
[  810.858828] ignition[879]: error at line 1, column 33486
[  810.858828] no filesystem specified
[  810.858918] ignition[879]: error at line 1, column 41160
[  810.858918] no filesystem specified
[  810.859086] ignition[879]: error at line 1, column 41328
[  810.859086] no filesystem specified
[  810.859268] ignition[879]: error at line 1, column 41556
[  810.859268] no filesystem specified
[  OK  ] Stopped dracut pre-mount hook.
[  OK  ] Stopped dracut initqueue hook.
[  811.222367] systemd[1]: Stopped dracut pre-mount hook.
[[  811.236667] ignition[879]: error at line 1, column 43726
[  811.236667] no filesystem specified
  OK  ] Stopped dracut pre-trigger hook.
[[  811.258269] systemd[1]: Stopped dracut initqueue hook.
  OK  ] Stopped dracut pre-udev hook.
[  OK  [  811.281441] ignition[879]: error at line 1, column 47349
[  811.281441] no filesystem specified
] Stopped dracut cmdline hook.
[  811.304241] systemd[1]: Stopped dracut pre-trigger hook.
[[  811.315529] ignition[879]: error at line 1, column 48469
[  811.315529] no filesystem specified
  OK  ] Stopped dracut ask for additional cmdline parameters.
[  811.339333] systemd[1]: Stopped dracut pre-udev hook.
         [  811.350392] ignition[879]: error at line 1, column 49968
[  811.350392] no filesystem specified
Starting Setup Virtual Console...
[  811.350459] systemd[1]: Stopped dracut cmdline hook.
[  811.369740] ignition[879]: error at line 1, column 52586
[  811.369740] no filesystem specified
[  OK  ] Stopped target Basic System.
[  811.421542] systemd[1]: Stopped dracut ask for additional cmdline parameters.
[  811.422236] ignition[879]: error at line 1, column 54430
[  811.422236] no filesystem specified
[  811.422332] systemd[1]: Starting Setup Virtual Console...
[  811.422446] ignition[879]: error at line 1, column 72745
[  811.422446] no filesystem specified
[  811.422520] systemd[1]: Stopped target Basic System.
[  811.422601] ignition[879]: error at line 1, column 74307
[  811.422601] no filesystem specified
[  811.422673] systemd[1]: Stopped target System Initialization.
[  811.422751] ignition[879]: error at line 1, column 79226
[  811.422751] no filesystem specified
[  811.422827] ignition[879]: error at line 1, column 82509
[  811.422827] no filesystem specified
[  811.423007] ignition[879]: error at line 1, column 82669
[  811.423007] no filesystem specified
[  811.423393] ignition[879]: error at line 1, column 82902
[  811.423393] no filesystem specified
[  811.423466] ignition[879]: error at line 1, column 88874
[  811.423466] no filesystem specified
[  811.423538] ignition[879]: error at line 1, column 103279
[  811.423538] no filesystem specified
[  811.423606] ignition[879]: error at line 1, column 104017
[  811.423606] no filesystem specified
[  811.423683] ignition[879]: error at line 1, column 104153
[  811.423683] no filesystem specified
[  811.423842] ignition[879]: error at line 1, column 105265
[  811.423842] no filesystem specified
[  811.424214] ignition[879]: error at line 1, column 105719
[  811.424214] no filesystem specified
[  811.424318] ignition[879]: error at line 1, column 105995
[  811.424318] no filesystem specified
[  811.424399] ignition[879]: error at line 1, column 115451
[  811.424399] no filesystem specified
[  811.424466] ignition[879]: error at line 1, column 116790
[  811.424466] no filesystem specified
[  811.424534] ignition[879]: failed to fetch config: config is not valid
[  811.424602] ignition[879]: failed to acquire config: config is not valid
[  811.424713] ignition[879]: Ignition failed: config is not valid
```

**Comment by jichenjc** [comment] 2019-11-29 08:18
I switched to commit db041b7d361449ffc2a616d2e99e343312ff1590 (Nov 1)
to give a try but nothing helpful ...

**Comment by jichenjc** [comment] 2019-11-29 08:43
https://github.com/openshift/os/issues/394 opened on coreos for further info

**Comment by sferich888** [comment] 2019-12-02 02:54
I can't trace this down, so I am hoping @wking or @abhinavdahiya can. But I feel like the issue here, is with the machineconfig or the machine definition - created by the installer, not with RHCOS or ignition. 

see: https://github.com/openshift/os/issues/394#issuecomment-560192997 

In short, the bootstrap.ign file has `filesystem` references, because these come from terrraform. However the master.ign (from the fake machineconfig role), does not! This is what causes the issues were seeing.

**Comment by jichenjc** [comment] 2019-12-02 07:13
Thanks for the info, I used the validation and got same result,

this is the master.ign
"storage":{"files":[{"group":{},"overwrite":true,"path":"/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt","user":{},"contents":{"source":"data:,","verification":{}},"mode":384},

this is the bootstrap.ign
"storage":{"files":[{"filesystem":"root","path":"/etc/containers/registries.conf","user":{"name":"root"},"contents":{"source":"data:text/plain;charset=utf-8;base64,","verification":{}},"mode":384},{

so I will try wit hthe filesystem and see whether it's helpful or not

as this seems not coreos issue, I closed that one and copied comments there to here

**Comment by jichenjc** [comment] 2019-12-02 08:10
@wking @abhinavdahiya 
I checked the machine-config-operator and seems that's just a server side read MachineConfig and marshal then return, so the master.ign should still be mainly created in installer side? 

If I do bin/openshift-install create  ignition-configs
then the master.ign doesn't contain too much helpful info, so those info should be created on the installer, is it created at pkg/asset/machines/master.go? 

Thanks

**Comment by slintes** [comment] 2019-12-02 12:23
not sure if I have the same root cause, but I see this in journal of master, does it help debugging this?
```
[    3.338714] localhost systemd[1]: Found device /dev/disk/by-label/root.                                                                                                                                                                            
[    3.374846] localhost systemd[1]: Started udev Wait for Complete Device Initialization.                                                                                                                                                            
[    3.380233] localhost systemd[1]: Starting Device-Mapper Multipath Device Controller...                                                                                                                                                            
[    3.385260] localhost systemd[1]: Reached target Initrd Root Device.                                                                                                                                                                               
[    3.389662] localhost systemd[1]: Started Device-Mapper Multipath Device Controller.                                                                                                                                                               
[    3.393639] localhost multipathd[988]: --------start up--------                                                                                                                                                                                    
[    3.393639] localhost multipathd[988]: read /etc/multipath.conf                                                                                                                                                                                    
[    3.399456] localhost systemd[1]: Reached target Local File Systems (Pre).                                                                                                                                                                         
[    3.403542] localhost multipathd[988]: /etc/multipath.conf does not exist, blacklisting all devices.                                                                                                                                               
[    3.403542] localhost multipathd[988]: You can run "/sbin/mpathconf --enable" to create                                                                                                                                                            
[    3.403542] localhost multipathd[988]: /etc/multipath.conf. See man mpathconf(8) for more details                                                                                                                                                  
[    3.403542] localhost multipathd[988]: /etc/multipath.conf does not exist, blacklisting all devices.                                                                                                                                               
[    3.403542] localhost multipathd[988]: You can run "/sbin/mpathconf --enable" to create                                                                                                                                                            
[    3.403542] localhost multipathd[988]: /etc/multipath.conf. See man mpathconf(8) for more details                                                                                                                                                  
[    3.403542] localhost multipathd[988]: path checkers start up                                                                                                                                                                                      
[    3.447567] localhost systemd[1]: Reached target Local File Systems.
[    3.451739] localhost systemd[1]: Starting Create Volatile Files and Directories...
[    3.454569] localhost iscsid[996]: iscsid: can't open InitiatorName configuration file /etc/iscsi/initiatorname.iscsi
[    3.454569] localhost iscsid[996]: iscsid: Warning: InitiatorName file /etc/iscsi/initiatorname.iscsi does not exist or does not contain a properly formatted InitiatorName. If using software iscsi (iscsi_tcp or ib_iser) or partial offload (bnx
2i or cxgbi iscsi), you may not be able to log into or discover targets. Please create a file /etc/iscsi/initiatorname.iscsi that contains a sting with the format: InitiatorName=iqn.yyyy-mm.<reversed domain name>[:identifier].
[    3.454569] localhost iscsid[996]: Example: InitiatorName=iqn.2001-04.com.redhat:fc6.
[    3.454569] localhost iscsid[996]: If using hardware iscsi like qla4xxx this message can be ignored.
[    3.454569] localhost iscsid[996]: iscsid: can't open InitiatorAlias configuration file /etc/iscsi/initiatorname.iscsi
[    3.492917] localhost systemd-tmpfiles[995]: [/usr/lib/tmpfiles.d/systemd.conf:11] Unknown group 'utmp'.
[    3.498476] localhost systemd[1]: Starting Open-iSCSI...
[    3.502448] localhost systemd[1]: Started Open-iSCSI.
[    3.506408] localhost systemd[1]: Started Create Volatile Files and Directories.
[    3.509800] localhost systemd[1]: Reached target System Initialization.
[    3.515723] localhost systemd-journald[232]: Missed 27 kernel messages
[    3.509752] localhost kernel: loop: module loaded
[    3.515861] localhost systemd[1]: Reached target Basic System.
[    3.520138] localhost systemd[1]: Starting CoreOS LUKS Opener...
[    3.522871] localhost coreos-cryptfs[998]: Device /dev/disk/by-partlabel/luks_root doesn't exist or access denied.
[    3.528583] localhost systemd[1]: Starting dracut initqueue hook...
[    3.533502] localhost coreos-cryptfs[998]: Device /dev/disk/by-partlabel/luks_root doesn't exist or access denied.
[    3.533529] localhost systemd[1]: Started dracut initqueue hook.
[    3.533610] localhost systemd[1]: Starting dracut pre-mount hook...
[    3.533631] localhost systemd[1]: Reached target Remote File Systems (Pre).
[    3.533648] localhost systemd[1]: Reached target Remote File Systems.
[    3.533665] localhost systemd[1]: Started dracut pre-mount hook.
[    3.533683] localhost systemd[1]: Starting File System Check on /dev/disk/by-label/root...
[    3.540401] localhost coreos-cryptfs[998]: parse error: Invalid numeric literal at line 1, column 15
[    3.559252] localhost coreos-cryptfs[998]: Device /dev/disk/by-partlabel/luks_root doesn't exist or access denied.
[    3.564837] localhost systemd[1]: coreos-luks-open.service: Main process exited, code=exited, status=1/FAILURE
[    3.570813] localhost systemd-fsck[1036]: /usr/sbin/fsck.xfs: XFS file system.
[    3.575179] localhost coreos-cryptfs[998]: coreos-cryptfs: FAILED to open /dev/disk/by-partlabel/luks_root
[    3.579194] localhost systemd[1]: coreos-luks-open.service: Failed with result 'exit-code'.
[    3.579247] localhost systemd[1]: Failed to start CoreOS LUKS Opener.
[    3.586265] localhost systemd[1]: Dependency failed for Initrd Default Target.
[    3.590113] localhost systemd[1]: initrd.target: Job initrd.target/start failed with result 'dependency'.
[    3.594159] localhost systemd[1]: initrd.target: Triggering OnFailure= dependencies.
[    3.594177] localhost systemd[1]: coreos-luks-open.service: Triggering OnFailure= dependencies.
```
There is no `/dev/disk/by-partlabel/luks_root`, but `/dev/disk/by-partlabel/root` (without luks_)

**Comment by sferich888** [comment] 2019-12-02 12:40
Don't think this is the same root cause, this looks like a new issue.

**Comment by slintes** [comment] 2019-12-02 13:37
ok
btw, using the same installer but an older OCP version works for me...
```
$ openshift-install version                       
openshift-install unreleased-master-2104-g98dcac423d53c187726140e21ed88af69c865de1
built from commit 98dcac423d53c187726140e21ed88af69c865de1

$ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.3.0-0.nightly-2019-11-25-153929   True        False         41s     Cluster version is 4.3.0-0.nightly-2019-11-25-153929
```

**Comment by jichenjc** [comment] 2019-12-02 13:47
ok, I did switch to Nov 1 commit but got same error, maybe need try again

**Comment by sferich888** [comment] 2019-12-02 16:54
@abhinavdahiya I wonder if https://github.com/openshift/os/issues/394#issuecomment-560482029 still applies and it this issue should reside not with the installer, but with some other OpenShift component. 

I just don't know where the master.ign > from the Machine config operator is generated or created, so IDK what repo to send this issue to.

**Comment by abhinavdahiya** [comment] 2019-12-02 17:04
The underlying issue is known https://github.com/openshift/installer/issues/2632

`registry.svc.ci.openshift.org/origin/release:4.3` release image has OKD content and needs to be installed using the installer from https://github.com/openshift/okd

Therefore any installs of OCP using master/ other release braches requires the user override the release image to OCP one.

Closing this to keep single OKD-OCP builds from master.

/close

**Closed by abhinavdahiya** 2019-12-02 17:04 UTC

**Comment by jichenjc** [comment] 2019-12-17 07:04
@abhinavdahiya I used https://github.com/openshift/okd/releases but it
provided me the only choices are 
 aws
  gcp
> openstack

if I am planning to use libvirt, what's the choice here? Thanks

**Comment by prabhatkarki** [comment] 2020-01-01 20:14
I'm also at the same point. the openshift-install binary from okd release doesn't give choice for libvirt.

**Comment by hassenius** [comment] 2020-01-08 12:51
@jichenjc 
> I checked the machine-config-operator and seems that's just a server side read MachineConfig and marshal then return, so the master.ign should still be mainly created in installer side?

I'm having the same issue on Azure as per https://github.com/openshift/installer/issues/2856

One thing I'm noticing is that if I ssh to the bootstrap machine of the openshift cluster and manually edit the `/etc/mcs/bootstrap/machine-configs/rendered-master-*.yaml` file to include `filesystem: root` this is not included in the resulting json from `curl --insecure https://localhost:22623/config/master` (however other modifications are).

So it appears to me this field is silently stripped by https://github.com/openshift/machine-config-operator

Does this point to some incorrect behaviour in mcahine-config-operator that has previously been accepted by coreos but no longer is?

**Comment by jichenjc** [comment] 2020-01-10 05:05
um.. not sure it's simliar issue, I doubt whether it's the coreos ignition version incompatible ..but no clue now
