### ISSUE TITLE
Allow creating multiple worker machine pools

### ISSUE THREAD

**Issue by OchiengEd** [openshift/installer#7021] opened 2023-03-23 22:21 UTC
# Version

```console
➜  ocp openshift-install version
openshift-install 4.12.8
built from commit f13d588191eca30b44be8ec0e77856f5946e4b72
release image quay.io/openshift-release-dev/ocp-release@sha256:28358de024c01a449b28f27fb4c122f15eb292a2becdf7c651511785c867884a
release architecture amd64
```

# Platform:
Platform: AWS
Type: IPI (Installer provisioned infrastructure)

# What happened?
Encountered an error when attempting to create multiple compute machine pools with different configuration. See snippet below from my `install-config.yaml`:

```yaml
apiVersion: v1
baseDomain: example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
- architecture: amd64
  hyperthreading: Enabled
  name: worker1
  platform:
    aws:
      type: m5.xlarge
  replicas: 2
...
```

The specific error is shown below:

```console
➜  openshift-install create cluster                                                                           
ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: compute[1].name: Unsupported value: "worker1": supported values: "worker" 
➜  
```

Unfortunately, changing the value of `compute[1].name` to "worker" results in a subsequent error which outlines the value of the name field is duplicated

```console
➜  openshift-install create cluster
WARNING failed to parse first occurence of unknown field: failed to unmarshal install-config.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field "region" 
INFO Attempting to unmarshal while ignoring unknown keys because strict unmarshaling failed 
ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: compute[1].name: Duplicate value: "worker" 
➜  
```

# What you expected to happen?

I expected to have an OpenShift cluster with five worker nodes; two of which will have a size of m5.xlarge.

# How to reproduce it (as minimally and precisely as possible)?

1. Create new install-config.yaml using the openshift-install binary.

```console
➜  ocp openshift-install create install-config
```

Select SSH public key, platform (alibabacloud, aws, azure, ...), region (us-east-1 in my case) , base domain , etc.

2. Open the resulting install-config.yaml in an editor of your choice to add a new compute machine pool

3. Attempt to create your  cluster

```console
➜  openshift-install create cluster
```

# Anything else we need to know?

N/A

# References

- enter text here.

**Comment by OchiengEd** [comment] 2023-04-04 20:23
Hi @patrickdillon, thank you for the response. Any chance this process is documented somewhere?

Also, is this something you foresee being worked on in the near future?

**Comment by patrickdillon** [comment] 2023-04-04 23:27
Documented here: https://docs.openshift.com/container-platform/4.12/machine_management/creating_machinesets/creating-machineset-aws.html

You can use the existing machinesets (from `oc describe machineset`) as a guide.

We will not work on this in the near future: we purposefully don't allow it because it introduces additional failure points which are unnecessary to the install. By design we defer as much as possible to day 2.

I am going to close this, but please feel free to add additional questions/input.

**Closed by patrickdillon** 2023-04-04 23:27 UTC
