### ISSUE TITLE
Installer for libvirt fails with multiple "the server does not recognize this resource" messages

### ISSUE THREAD

**Issue by samson7point1** [openshift/installer#2043] opened 2019-07-18 15:34 UTC
# Version
```console
# bin/openshift-install version
bin/openshift-install unreleased-master-1317-gb6cf5482610dafe61b8946acabef96a22733f294-dirty
built from commit b6cf5482610dafe61b8946acabef96a22733f294
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

libvirt

# What happened?
The installer failed with a fatal warning "failed to initialize the cluster: Multiple errors are preventing progress"
```INFO Fetching OS image: rhcos-420.8.20190708.2-qemu.qcow2 
INFO Creating infrastructure resources...         
INFO Waiting up to 3h0m0s for the Kubernetes API at https://api.swlab.lab.samsonwick.com:6443... 
INFO API v1.14.0+6792851 up                       
INFO Waiting up to 3h0m0s for bootstrapping to complete... 
INFO Destroying the bootstrap resources...        
INFO Waiting up to 1h0m0s for the cluster at https://api.swlab.lab.samsonwick.com:6443 to initialize... 
FATAL failed to initialize the cluster: Multiple errors are preventing progress:
* Could not update oauthclient "console" (252 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-apiserver-operator/openshift-apiserver-operator" (426 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-authentication-operator/authentication-operator" (394 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-cluster-version/cluster-version-operator" (6 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-controller-manager-operator/openshift-controller-manager-operator" (430 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-image-registry/image-registry" (400 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-kube-apiserver-operator/kube-apiserver-operator" (410 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-kube-controller-manager-operator/kube-controller-manager-operator" (414 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-kube-scheduler-operator/kube-scheduler-operator" (418 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-machine-api/cluster-autoscaler-operator" (144 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-machine-api/machine-api-operator" (95 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-operator-lifecycle-manager/olm-operator" (420 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator" (403 of 431): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-service-catalog-controller-manager-operator/openshift-service-catalog-controller-manager-operator" (406 of 431): the server does not recognize this resource, check extension API servers 
```
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?
The installation to complete successfully

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

No

# References

Not that I can tell

**Comment by zeenix** [comment] 2019-07-19 09:50
Most likely a duplicate of #1893 .

/close

**Closed by zeenix** 2019-07-19 09:50 UTC
Labels: platform/libvirt
