### ISSUE TITLE
Cannot build from master !! ??

### ISSUE THREAD

**Issue by droslean** [openshift/installer#619] opened 2018-11-06 12:38 UTC
```console
$ ./hack/build.sh 
+ LAUNCH_PATH=/root/go/src/github.com/openshift/installer
++ dirname ./hack/build.sh
+ cd ./hack/..
++ go list -e -f '{{.Dir}}' github.com/openshift/installer
+ PACKAGE_PATH=/root/go/src/github.com/openshift/installer
+ test -z /root/go/src/github.com/openshift/installer
+ LOCAL_PATH=/root/go/src/github.com/openshift/installer
+ test /root/go/src/github.com/openshift/installer '!=' /root/go/src/github.com/openshift/installer
+ MODE=release
++ git describe --always --abbrev=40 --dirty
+ LDFLAGS=' -X main.version=v0.3.0-145-g6106d58ddf61f3f18c51f6b295ab8c73160dac91'
+ TAGS=
+ OUTPUT=bin/openshift-install
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ case "${MODE}" in
+ TAGS=' release'
+ test '' '!=' y
+ go generate ./data
writing assets_vfsdata.go
+ echo ' release'
+ grep -q libvirt_destroy
+ go build -ldflags ' -X main.version=v0.3.0-145-g6106d58ddf61f3f18c51f6b295ab8c73160dac91' -tags ' release' -o bin/openshift-install ./cmd/openshift-install
# github.com/openshift/installer/vendor/k8s.io/client-go/transport
vendor/k8s.io/client-go/transport/round_trippers.go:437:9: undefined: strings.Builder
```

**Comment by droslean** [comment] 2018-11-06 12:45
That start happening after #579

**Comment by droslean** [comment] 2018-11-06 13:16
It seems that the go versions should be higher than 1.9. Is this documented anywhere? 
Also the `hack/build.sh` should check that before continuing.

**Comment by wking** [comment] 2018-11-06 22:57
> It seems that the go versions should be higher than 1.9. Is this documented anywhere?

[`strings.Builder`][1] is new in Go 1.10.  With [Go 1.11 released in August][2] upstream [dropped support for 1.9][3].  Do we want to document/advertise support for deprecated Go releases?  The version that we *do* support is documented [here][4], and that declaration:

* Is backed by CI, ensuring that it works.
* Is something users can invoke locally if they have issues building the installer on their host system.

[1]: https://golang.org/pkg/strings/#Builder
[2]: https://golang.org/doc/devel/release.html#go1.11
[3]: https://golang.org/doc/devel/release.html#policy
[4]: https://github.com/openshift/installer/blob/8ef57585ccc79b3ac54da7f0757593d4c6a54e70/images/installer/Dockerfile.ci#L4

**Comment by DanyC97** [comment] 2018-11-06 23:39
@wking imo will be good to document it in a `md` file - even if that is in `hack` dir or something rather than wait for people to look in the dockerfile

**Comment by wking** [comment] 2018-11-06 23:48
Also, cross-linking #589.

> imo will be good to document it in a md file...

So in this case, the Go 1.10 floor is due to a vendor bump.  Do you think we should be manually pulling deps like that from our vendored packages?  We vendor a bunch of packages, and that seems like a lot of work.

Or do you think we should list a minimum version and test that version in CI?  Maintaining CI tooling for multiple Go versions also sounds like a lot of work.  Would you run e2e tests on installers built with each Go version (crossed with different versions of our other dependencies?  Kernel versions?  Once we test them, libvirt versions?).

> - even if that is in hack dir or something rather than wait for people to look in the dockerfile

If the issue is "folks are having trouble building the installer", using a Dockerfile approach with versions that work and pass CI is something we're already doing.  And while it's a bit unfortunate that folks are on their own as far as other versions go, there's only so much we currently have time to maintain.  Would you be ok with a link from `docs/dev/dependencies.md` to `images/installer/Dockerfile.ci` to make the Dockerfile more discoverable?

**Comment by droslean** [comment] 2018-11-07 13:18
opened #621

**Comment by raesene** [comment] 2018-11-16 13:04
This would be well worth documenting.  I'm following the "happy path" install for libvirt on a vanilla CentOS 7 VM and it fails due to this issue.  the current build pre-requisites instruction is to install the `golang-bin` package via yum and this doesn't work as CentOS provides `golang-bin-1.9.4-1.el7.x86_64`

**Closed** 2018-12-07 14:06 UTC

**Comment by DanyC97** [comment] 2018-12-17 17:57
@wking 

> Would you be ok with a link from docs/dev/dependencies.md to images/installer/Dockerfile.ci to make the Dockerfile more discoverable?

yes i'd say
