### ISSUE TITLE
Openshift Installer fail to create VMs in vsphere. Errors with "Invalid template interpolation value"

### ISSUE THREAD

**Issue by srirkann** [openshift/installer#2401] opened 2019-09-24 17:24 UTC
# Version
Terraform v0.12.9
+ provider.external v1.2.0
+ provider.ignition v1.1.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.vsphere v1.12.0

The vsphere version is 6.5

```console
$ openshift-install version
openshift-install v4.1.16-201909100604-dirty
built from commit 7c3908a694fa7401ae5a8c34ac5942d7dbfd7092
release image quay.io/openshift-release-dev/ocp-release@sha256:61ed953962d43cae388cb3c544b4cac358d4675076c2fc0befb236209d5116f7
```

# Platform:
None( UPI for Vsphere

# What happened?
After creating the ignition resources and updating the terraform.tfvars files when I apply terraform apply - auto-approve, the terraform script fails with the below error 

===========================
module.compute.data.vsphere_datastore.datastore: Refreshing state...
module.control_plane.data.vsphere_network.network: Refreshing state...
module.bootstrap.data.vsphere_virtual_machine.template: Refreshing state...
module.resource_pool.data.vsphere_compute_cluster.compute_cluster: Refreshing state...

Error: Invalid template interpolation value

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  28: 
  29: 
  30: 
  31: 
  32: 
  33: 
  34: IPADDR=${local.ip_addresses[count.index]}
  35: 
  36: 
  37: 
  38: 
  39: 
    |----------------
    | count.index is 0
    | local.ip_addresses is tuple with 1 element
==============================================

# What you expected to happen?
The terraform script should deploy the vm and bring up the environment in vsphere

# How to reproduce it (as minimally and precisely as possible)?
Followed the procedure as defined in the link https://github.com/openshift/installer/tree/release-4.1/upi/vsphere
1. Create an install-config.yaml.
2. Run openshift-install create ignition-configs.
3. Fill out a terraform.tfvars file with the ignition configs generated
4. Run terraform init.
5. Run terraform apply -auto-approve. The terraform apply fails
Error: Invalid template interpolation value

**Comment by srirkann** [comment] 2019-09-24 17:25
The control_plane_ips = ["10.225.90.181","10.225.90.182","10.225.90.183"]
compute_ips =  ["10.225.90.184","10.225.90.185","10.225.90.186"]

**Comment by srirkann** [comment] 2019-09-24 18:39
I got it working with a workaround of modifying 
 IPADDR=${ip_addresses[count.index]}

**Comment by abhinavdahiya** [comment] 2019-09-25 16:47
This looks like a duplicate of https://github.com/openshift/installer/issues/2183

/close

**Closed by abhinavdahiya** 2019-09-25 16:47 UTC

**Comment by arunabhabanerjee** [comment] 2019-12-10 20:53
I am also facing this issue. Please help.

Terraform v0.12.17
+ provider.external v1.2.0
+ provider.ignition v1.2.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.vsphere v1.13.0

Error:
Error: Invalid template interpolation value

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  28:
  29:
  30:
  31:
  32:
  33:
  34: IPADDR=${local.ip_addresses[count.index]}
  35:
  36:
  37:
  38:
  39:
    |----------------
    | count.index is 0
    | local.ip_addresses is tuple with 1 element

Cannot include the given value in a string template: string required.


Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR=${local.ip_addresses[count.index]}
    |----------------
    | count.index is 1
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.


Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR=${local.ip_addresses[count.index]}
    |----------------
    | count.index is 2
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.


Error: Invalid template interpolation value

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  28:
  29:
  30:
  31:
  32:
  33:
  34: IPADDR=${local.ip_addresses[count.index]}
  35:
  36:
  37:
  38:
  39:
    |----------------
    | count.index is 0
    | local.ip_addresses is tuple with 1 element

Cannot include the given value in a string template: string required.


Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR=${local.ip_addresses[count.index]}
    |----------------
    | count.index is 2
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.


Error: Invalid template interpolation value

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  28:
  29:
  30:
  31:
  32:
  33:
  34: IPADDR=${local.ip_addresses[count.index]}
  35:
  36:
  37:
  38:
  39:
    |----------------
    | count.index is 0
    | local.ip_addresses is tuple with 1 element

Cannot include the given value in a string template: string required.


Error: Invalid index

  on machine/ignition.tf line 34, in data "ignition_file" "static_ip":
  34: IPADDR=${local.ip_addresses[count.index]}
    |----------------
    | count.index is 1
    | local.ip_addresses is tuple with 1 element

The given key does not identify an element in this collection value.

root:/home/arunabha/vsphere>


availability_zone = "${data.aws_availability_zones.available.names[count.index]}"

IPADDR=${local.ip_addresses[count.index]}
