### ISSUE TITLE
openshift-install keep failing on Azure with error Could not update servicemonitor "openshift-apiserver-operator/openshift-apiserver-operator" 

### ISSUE THREAD

**Issue by nichochen** [openshift/installer#1824] opened 2019-06-06 07:49 UTC
# Version
./openshift-install unreleased-master-1088-g273cece0ea05bd55ac7d03c5c3022255ea4fd5f7-dirty
built from commit 273cece0ea05bd55ac7d03c5c3022255ea4fd5f7
release image quay.io/openshift-release-dev/ocp-release@sha256:8d51bc2da4b9873053b2b3f0737c912ba1e0623ff4b303f1a8ec3618ba3354ff

# Platform (aws|libvirt|openstack):
Azure

# What happened?
Creating cluster keep failing as following. Azure region: centralus and eastus.

./openshift-install create install-config
./openshift-install create cluster
INFO Consuming "Install Config" from target directory
INFO Creating infrastructure resources...
INFO Waiting up to 30m0s for the Kubernetes API at https://api.hello.xxx.org:6443...
INFO API v1.14.0+70479e3 up
INFO Waiting up to 30m0s for bootstrapping to complete...
INFO Destroying the bootstrap resources...
INFO Waiting up to 30m0s for the cluster at https://api.hello.xxx.org:6443 to initialize...
FATAL failed to initialize the cluster: Multiple errors are preventing progress:
* Could not update servicemonitor "openshift-apiserver-operator/openshift-apiserver-operator" (369 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-authentication-operator/authentication-operator" (344 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-controller-manager-operator/openshift-controller-manager-operator" (372 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-image-registry/image-registry" (350 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-kube-apiserver-operator/kube-apiserver-operator" (360 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-kube-controller-manager-operator/kube-controller-manager-operator" (363 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-kube-scheduler-operator/kube-scheduler-operator" (366 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-operator-lifecycle-manager/olm-operator" (272 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator" (353 of 373): the server does not recognize this resource, check extension API servers
* Could not update servicemonitor "openshift-service-catalog-controller-manager-operator/openshift-service-catalog-controller-manager-operator" (356 of 373): the server does not recognize this resource, check extension API servers: timed out waiting for the condition

# What you expected to happen?

Installation finished with no error.

# How to reproduce it (as minimally and precisely as possible)?

Follow the instructions to create a cluster on Azure.
https://github.com/openshift/installer/tree/master/docs/user/azure

# Anything else we need to know?

Enter text here.

# References

**Comment by abhinavdahiya** [comment] 2019-06-06 13:54
duplicate of https://github.com/openshift/installer/issues/1817

/close

**Closed by abhinavdahiya** 2019-06-06 13:54 UTC
