### ISSUE TITLE
Additional vSphere permissions needed for IPI install

### ISSUE THREAD

**Issue by aarongreen85** [openshift/installer#5298] opened 2021-10-15 17:03 UTC
# Version

```console
$ ./openshift-install version
./openshift-install 4.8.13
built from commit 450e95767d89f809cb1afe5a142e9c824a269de8
release image quay.io/openshift-release-dev/ocp-release@sha256:5d396ad7d5f3cb527580c735e87dfd3b853bbb531e7f03e3a184d0accc223cdf
```

# Platform:

vSphere 7.0.2

IPI
# What happened?

Ran through multiple installs with errors related to permissions needed that are not documented.
```
ERROR
ERROR Error: failed to mark vm as template: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-053661408/main.tf line 44, in resource "vsphereprivate_import_ova" "import":
ERROR   44: resource "vsphereprivate_import_ova" "import" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```
```
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/bootstrap/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/master/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/master/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/master/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```
Additional looking through vSphere logs determined that additional permissions were needed.
```
Privilege check failed for user VSPHERE.LOCAL\service-account for missing permission VirtualMachine.Provisioning.MarkAsTemplate.
```
```
Privilege check failed for user VSPHERE.LOCAL\service-account for missing permission VirtualMachine.Provisioning.DeployTemplate.
```

# What you expected to happen?

Installed and running Openshift cluster on my vSphere cluster

# How to reproduce it (as minimally and precisely as possible)?

Add role and service account in vSphere as described within documentation. Run through install.

# Anything else we need to know?

Permissions that need added are as follows -

`VirtualMachine.Provisioning.MarkAsTemplate`
`VirtualMachine.Provisioning.DeployTemplate`

**Comment by staebler** [comment] 2021-10-22 02:31
@rvanderp3 Was it intentional that the `VirtualMachine.Provisioning.MarkAsTemplate` and `VirtualMachine.Provisioning.DeployTemplate` permissions were only added as needed when the installer is creating the folder? Is the assumption that the user would have the permissions at the folder level already when they are providing an existing folder to the installer?

**Comment by aarongreen85** [comment] 2021-11-16 01:29
I believe this issue could then be solved by making this docs directory point to the openshift-docs repo. I'm going to submit a PR that does just that.

**Comment by saintdle** [comment] 2021-12-15 01:08
This issue is also seen on 4.9.10 when installing into a VMware Cloud on AWS (VMC) environment using the cloudadmin@vmc.local account. This account cannot be given any more permissions, as it is the main administrator customer facing account. 

````
ERROR Error: failed to create import spec: ServerFaultCode: Permission to perform this operation was denied. 
ERROR   on ../../../tmp/openshift-install--860567841/main.tf line 44, in resource "vsphereprivate_import_ova" "import": ERROR   44: resource "vsphereprivate_import_ova" "import" { 
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change 
````

**Comment by saintdle** [comment] 2021-12-20 18:28
> This issue is also seen on 4.9.10 when installing into a VMware Cloud on AWS (VMC) environment using the [cloudadmin@vmc.local](mailto:cloudadmin@vmc.local) account. This account cannot be given any more permissions, as it is the main administrator customer facing account.
> 
> ```
> ERROR Error: failed to create import spec: ServerFaultCode: Permission to perform this operation was denied. 
> ERROR   on ../../../tmp/openshift-install--860567841/main.tf line 44, in resource "vsphereprivate_import_ova" "import": ERROR   44: resource "vsphereprivate_import_ova" "import" { 
> FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change 
> ```
> 
> I can confirm the account has the privileges needed:
> 
>     * VirtualMachine.Provisioning.MarkAsTemplate
> 
>     * VirtualMachine.Provisioning.DeployTemplate
> 
> 
> ![image](https://user-images.githubusercontent.com/22192242/146107209-766d1491-b7b0-4670-8c41-3cd0b591e8f2.png)

Turns out this issue was caused by an upgrade issue with the VMC SDDC in my environment where the correct permissons were not assigned to existing VM Networks. This was resolved in my environment by the VMware Support Team.

**Closed** 2022-07-27 19:40 UTC
Labels: platform/vsphere
