### ISSUE TITLE
Cannot deploy on libvirt, referencing ../tmp directory

### ISSUE THREAD

**Issue by yrobla** [openshift/installer#2702] opened 2019-11-21 12:36 UTC
# Version

```console
$ openshift-install version
/root/.kni/testing.virt.edge-sites.net/requirements/openshift-install unreleased-master-1805-g425e4ff0037487e32571258640b39f56d5ee5572
built from commit 425e4ff0037487e32571258640b39f56d5ee5572
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:
libvirt
# What happened?

When running the deploy cluster command like that:
+ /root/.kni/testing.virt.edge-sites.net/requirements/openshift-install create cluster --dir=/root/.kni/testing.virt.edge-sites.net/final_manifests

I'm getting this error:

level=info msg="Creating infrastructure resources..."
level=error
level=error msg="Error: Unreadable module directory"
level=error
level=error msg="Unable to evaluate directory symlink: lstat ../tmp: no such file or directory"
level=error
level=error
level=error msg="Error: Failed to read module directory"
level=error
level=error msg="Module directory  does not exist or cannot be read."
level=error
level=error

What is this tmp directory? Do i need to execute some tmp directory creation before deploying the cluster? This happened to me when changing the openshift-install version from 4.1 to 4.2

**Comment by cgwalters** [comment] 2019-11-21 12:42
Likely a dup of https://github.com/openshift/installer/issues/1839

**Comment by yrobla** [comment] 2019-11-21 12:48
My directory is not a symlink... However, we deploy with a pre-generated set of yamls. We go with create cluster , taking some pre-generated files that are present on that directory. Can it be related to that?

**Comment by patrickdillon** [comment] 2019-11-21 14:43
which version of go are you using to compile the installer? there was discussion on the internal mailing list that this could be a bug handling symlinks in go 1.12 and you should updgrade to a newer go 1.12.z

**Comment by yrobla** [comment] 2019-11-21 15:20
No, it's newer: go version
go version go1.13.4 linux/amd64

**Comment by yrobla** [comment] 2019-11-27 15:25
Well the issue is different. I have my openshift-install binary on a folder called /root/.kni/testing.virt.edge-sites.net/requirements . If i run the libvirt installer from there, it fails.
In order to make it work, i need to move the binary to a directory 2 levels down from root (for example /usr/bin/) and run the installer from that directory. Then it works.
Can this relative reference be moved to an absolute one?

**Comment by abhinavdahiya** [comment] 2020-02-10 21:57
this is a duplicate of https://github.com/openshift/installer/issues/1839

/close

**Closed by abhinavdahiya** 2020-02-10 21:57 UTC
