### ISSUE TITLE
Cluster creation fails on Azure using Mac installer

### ISSUE THREAD

**Issue by amanohar** [openshift/installer#2069] opened 2019-07-23 00:16 UTC
# Version

```console
$ ./openshift-install version
./openshift-install unreleased-master-1088-g273cece0ea05bd55ac7d03c5c3022255ea4fd5f7-dirty
built from commit 273cece0ea05bd55ac7d03c5c3022255ea4fd5f7
release image quay.io/openshift-release-dev/ocp-release@sha256:8d51bc2da4b9873053b2b3f0737c912ba1e0623ff4b303f1a8ec3618ba3354ff
```

# Platform:
Azure

# What happened?
I downloaded the installer for Mac from: https://cloud.redhat.com/openshift and the cluster creation fails consistently at the same step. Master nodes are ready but worker nodes don't join the cluster.

`.openshift_install.log`:

> the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor

> time="2019-07-22T15:59:55-07:00" level=info msg="Waiting up to 30m0s for the cluster at https://api.aro4u0722c1.anubhuti.site:6443 to initialize..."
time="2019-07-22T15:59:55-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 82% complete"
time="2019-07-22T16:00:16-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056"
time="2019-07-22T16:00:16-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: downloading update"
time="2019-07-22T16:00:16-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056"
time="2019-07-22T16:00:16-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 23% complete"
time="2019-07-22T16:00:16-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 24% complete"
time="2019-07-22T16:00:31-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 78% complete"
time="2019-07-22T16:00:46-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 90% complete"
time="2019-07-22T16:01:02-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 91% complete"
time="2019-07-22T16:01:31-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 92% complete"
time="2019-07-22T16:03:46-07:00" level=debug msg="Still waiting for the cluster to initialize: Multiple errors are preventing progress:\n* Could not update servicemonitor \"openshift-apiserver-operator/openshift-apiserver-operator\" (369 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-authentication-operator/authentication-operator\" (344 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-controller-manager-operator/openshift-controller-manager-operator\" (372 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-image-registry/image-registry\" (350 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-apiserver-operator/kube-apiserver-operator\" (360 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-controller-manager-operator/kube-controller-manager-operator\" (363 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-scheduler-operator/kube-scheduler-operator\" (366 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-operator-lifecycle-manager/olm-operator\" (272 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator\" (353 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-controller-manager-operator/openshift-service-catalog-controller-manager-operator\" (356 of 373): the server does not recognize this resource, check extension API servers"
time="2019-07-22T16:10:46-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 93% complete"
time="2019-07-22T16:11:16-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.2.0-0.nightly-2019-06-03-135056: 94% complete"
time="2019-07-22T16:12:16-07:00" level=debug msg="Still waiting for the cluster to initialize: Multiple errors are preventing progress:\n* Could not update servicemonitor \"openshift-apiserver-operator/openshift-apiserver-operator\" (369 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-authentication-operator/authentication-operator\" (344 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-controller-manager-operator/openshift-controller-manager-operator\" (372 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-image-registry/image-registry\" (350 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-apiserver-operator/kube-apiserver-operator\" (360 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-controller-manager-operator/kube-controller-manager-operator\" (363 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-scheduler-operator/kube-scheduler-operator\" (366 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-operator-lifecycle-manager/olm-operator\" (272 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator\" (353 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-controller-manager-operator/openshift-service-catalog-controller-manager-operator\" (356 of 373): the server does not recognize this resource, check extension API servers"
time="2019-07-22T16:31:21-07:00" level=fatal msg="failed to initialize the cluster: Multiple errors are preventing progress:\n* Could not update servicemonitor \"openshift-apiserver-operator/openshift-apiserver-operator\" (369 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-authentication-operator/authentication-operator\" (344 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-controller-manager-operator/openshift-controller-manager-operator\" (372 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-image-registry/image-registry\" (350 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-apiserver-operator/kube-apiserver-operator\" (360 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-controller-manager-operator/kube-controller-manager-operator\" (363 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-scheduler-operator/kube-scheduler-operator\" (366 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-operator-lifecycle-manager/olm-operator\" (272 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator\" (353 of 373): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-controller-manager-operator/openshift-service-catalog-controller-manager-operator\" (356 of 373): the server does not recognize this resource, check extension API servers: timed out waiting for the condition"

# What you expected to happen?

OpenShift 4.x cluster should be successfully created on Azure.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/12838766/61673254-8d31ab00-aca3-11e9-8176-36aed289e0a8.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/12838766/61673295-b6ead200-aca3-11e9-992e-56804d601149.png">

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/12838766/61673318-d550cd80-aca3-11e9-92bb-18b593e2e581.png">

# How to reproduce it (as minimally and precisely as possible)?

Download installer from https://cloud.redhat.com/openshift and run the following on Mac:
```console
az login -t  <TENANT_ID>

az account set --subscription <SUB_ID>

export OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE="/resourceGroups/rhcos_images/providers/Microsoft.Compute/images/rhcos"

export CLUSTERNAME=<NAME>

./openshift-install create install-config --dir ~/.tmp/$CLUSTERNAME --log-level debug

./openshift-install create manifests --dir ~/.tmp/$CLUSTERNAME --log-level debug

./openshift-install create ignition-configs --dir ~/.tmp/$CLUSTERNAME --log-level debug

./openshift-install create cluster --dir ~/.tmp/$CLUSTERNAME --log-level debug
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by abhinavdahiya** [comment] 2019-07-23 05:34
/label platform/azure

1) Can you make sure the machines have actually being created.
2) Make sure you have approved the CSRs for the compute nodes joining.
   The tech preview installation had errors where the compute nodes don't join the cluster because the CSRs were not approved. See the note in https://github.com/openshift/installer/blob/master/docs/user/azure/install.md#create-cluster

3) you can try out the installer from the latest code by following the instructions here https://origin-release.svc.ci.openshift.org/releasestream/4.2.0-0.okd/release/4.2.0-0.okd-2019-07-22-195548 to download the installer binary.

**Comment by amanohar** [comment] 2019-07-23 14:08
cc: @mjudeikis 
1 Yes, the machines were created:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/12838766/61717640-56e14380-ad16-11e9-918e-279d24289f57.png">

2. The API server is now down (happens consistently a couple of hours after I create 4.x cluster)
>Unable to connect to the server: dial tcp 52.151.235.249:6443: i/o timeout

I can try to create another cluster to get to approve CSRs stage.

3. Installer on Mac seems to be broken for the last 1 week at least. I ran /hack/build.sh from master and create cluster fails: 
![image](https://user-images.githubusercontent.com/12838766/61718725-63669b80-ad18-11e9-8ec7-e92f8e2061b4.png)

I will try this: https://origin-release.svc.ci.openshift.org/releasestream/4.2.0-0.okd/release/4.2.0-0.okd-2019-07-22-195548

Logs:
>gn/T/openshift-install-641839823/plugins/terraform-provider-ignition" 
DEBUG Symlinking plugin terraform-provider-local src: "/Users/anubhuti/go/src/github.com/openshift/installer/bin/openshift-install" dst: "/var/folders/lp/pylwgl_x6gs16b61llvjndc40000gn/T/openshift-install-641839823/plugins/terraform-provider-local" 
DEBUG Initializing modules...                      
DEBUG - bootstrap in                               
DEBUG - dns in                                     
DEBUG - master in                                  
DEBUG - vnet in                                    
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
ERROR                                              
ERROR Error: Unreadable module directory           
ERROR                                              
ERROR Unable to evaluate directory symlink: lstat ../var: no such file or directory 
ERROR                                              
ERROR                                              
ERROR Error: Failed to read module directory       
ERROR                                              
ERROR Module directory  does not exist or cannot be read. 
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to initialize Terraform

**Comment by mjudeikis** [comment] 2019-07-23 15:52
User newest installer from cloud.redhat.com and got csr issue (as expected):

```
[mjudeiki@redhat openshift-azure]$ oc get csr
NAME        AGE     REQUESTOR                                                                   CONDITION
csr-2nd84   28m     system:node:mj-test-8t745-master-1                                          Approved,Issued
csr-6lpcv   7m26s   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-7z5tw   28m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-89hxr   28m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-b4gkl   10m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-bbkvx   19m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-cbglv   28m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-f6z6j   2m23s   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-fw6rl   28m     system:node:mj-test-8t745-master-2                                          Approved,Issued
csr-ngsf5   28m     system:node:mj-test-8t745-master-0                                          Approved,Issued
csr-qsv5w   14m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
```

after approval, I got fully working cluster. I suspect this is somehow related to where the installer is running

**Comment by chancez** [comment] 2019-07-23 16:59
I cannot reproduce this on my Mac. I tried the latest 4.2 https://openshift-release.svc.ci.openshift.org/releasestream/4.2.0-0.ci/release/4.2.0-0.ci-2019-07-22-175905 and I also regularly build the installer from master and install from that and haven't seen this.

**Comment by mjudeikis** [comment] 2019-07-23 17:07
golang version?

**Comment by abhinavdahiya** [comment] 2019-08-30 14:01
Cannot reproduce this on our end. Are you still seeing this error?

**Comment by abhinavdahiya** [comment] 2019-11-05 17:58
we can't reproduce this error on our end..

/close

this might be a duplicate of https://github.com/openshift/installer/issues/1839

**Closed by abhinavdahiya** 2019-11-05 17:58 UTC
Labels: platform/azure
