### ISSUE TITLE
No way to specify the availability zone for masters and workers for OpenStack

### ISSUE THREAD

**Issue by ITD27M01** [openshift/installer#3391] opened 2020-04-01 12:24 UTC
# Version

```console
 ../openshift-install version
../openshift-install 4.3.8
built from commit f7a2f7cf9ec3201bb8c9ebb677c05d21c72e3cc5
release image quay.io/openshift-release-dev/ocp-release@sha256:a414f6308db72f88e9d2e95018f0cc4db71c6b12b2ec0f44587488f0a16efc42
```

# Platform:

openstack

# What happened?
No way to specify the availability zone for masters and workers

# What you expected to happen?
There should be "zones" parameter to specify availability zone to deploy machines on. As for AWS.

# How to reproduce it (as minimally and precisely as possible)?

Try to deploy cluster on OpenStack.

**Comment by Fedosin** [comment] 2020-04-01 20:07
We plan to add availability zone support in version 4.6

**Comment by pierreprinetti** [comment] 2020-04-02 14:55
Closing as a duplicate of #2391.

Please reopen if you think it is a different issue.

/close

**Closed** 2020-04-02 14:56 UTC
Labels: platform/openstack
