### ISSUE TITLE
DNS seems to break when installing on GCP

### ISSUE THREAD

**Issue by pfischer8989** [openshift/installer#2378] opened 2019-09-19 03:57 UTC
# Version

```console
$ openshift-install version
./openshift-install v4.2.0
built from commit 2553a84b4f7f704f3eed20cc5ab0ef15572a1f24
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:1502ff409697a70aa11c1d9024e98f1ee069f8b866cc82c38ebebd5670892d70
```

# Platform:

The platform is GCP

# What happened?
The installer times out waiting for the Kubernetes API to come up. The Terraform build completed and all the Virtual machines, FW rules and DNS seems to get created properly. 

When i login to the master i see this in the kubernetes logs

Sep 19 03:38:48 glotka-tndgb-b.c.e-ocp4.internal bootkube.sh[1705]: https://etcd-1.glotka.arctiq-ocp4-demo.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-1.glotka.arctiq-ocp4-demo.com on 169.254.169.254:53: no such host
Sep 19 03:38:48 glotka-tndgb-b.c.e-ocp4.internal bootkube.sh[1705]: https://etcd-0.glotka.arctiq-ocp4-demo.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-0.glotka.arctiq-ocp4-demo.com on 169.254.169.254:53: no such host
Sep 19 03:38:48 glotka-tndgb-b.c.e-ocp4.internal bootkube.sh[1705]: https://etcd-2.glotka.arctiq-ocp4-demo.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-2.glotka.arctiq-ocp4-demo.com on 169.254.169.254:53: no such host
Sep 19 03:38:48 glotka-tndgb-b.c.e-ocp4.internal bootkube.sh[1705]: Error: unhealthy cluster
Sep 19 03:38:48 glotka-tndgb-b.c.e-ocp4.internal bootkube.sh[1705]: etcdctl failed. Retrying in 5 seconds...

I cannot resolve any of the etc hosts from the masters. Any ideas?? The zone and entries are there

# What you expected to happen?

Expected the OCP4 cluster to install on GCP

# How to reproduce it (as minimally and precisely as possible)?

Run the installer and create a cluster in GCP

```console
$ ./openshift-install create cluster --log-level debug
```

# Anything else we need to know?

It did work once two weeks ago. I have tried several different builds with the same result.

# References

- enter text here.

**Comment by abhinavdahiya** [comment] 2019-09-19 05:14
Can you provide the log bundle that was captured as part of failed install.

Also the .openshift_install.log

**Comment by pfischer8989** [comment] 2019-09-19 13:23
This is something with resolution from the private domain that gets created by terraform. I cannot seem to resolve anything from the subdomain on any VM on the internal network. They are authorized but no query is valid. 

Where does the log bundle get stored on the machines? The ssh to where i am running the installer also fails.

Attached is the openshift_install log. 
[openshift_install.log](https://github.com/openshift/installer/files/3631387/openshift_install.log)

**Comment by abhinavdahiya** [comment] 2019-09-19 13:57
> time="2019-09-19T08:23:27-04:00" level=error msg="Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the proper ssh key is in your keyring or specify with --key: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"

The installer will grab the logs from bootstrap-host when you already have ssh_agent configured with the key you provided during install or ~/.ssh/ to load the keys that can be used.

You can grab the same log by using..

 `openshift-install --dir <> gather bootstrap --key <path to the ssh key> `

**Comment by pfischer8989** [comment] 2019-09-19 14:55
Ok ran it for the 10th time and this time i was able to resolve DNS from the machines on the internal subdomain but it still failed. Here is the bundle logs. No idea why DNS decided to work this time.....i only changed the cluster name. 

[log-bundle-20190919105305.tar.gz](https://github.com/openshift/installer/files/3631883/log-bundle-20190919105305.tar.gz)

**Comment by abhinavdahiya** [comment] 2019-09-19 16:18
> Ok ran it for the 10th time and this time i was able to resolve DNS from the machines on the internal subdomain but it still failed. Here is the bundle logs. No idea why DNS decided to work this time.....i only changed the cluster name.
> 
> [log-bundle-20190919105305.tar.gz](https://github.com/openshift/installer/files/3631883/log-bundle-20190919105305.tar.gz)

1) the control-plane nodes logs are empty, that means the control-plane machines are not up.
2) also the bootstrap/containers/machine-config-server-a5e3e469f22eb9f2785d6cfd3482624ccaa2d49e2bb49757b4bae55c0e68030a.log log shows no requests, that means the control-plane hosts did not contact the bootstrap-host for their configuration.

Can you see the logs from the serial console of your control-plane? https://cloud.google.com/compute/docs/instances/viewing-serial-port-output

**Comment by pfischer8989** [comment] 2019-09-19 17:24
Sorry but what did you mean by this? 

"no requests, that means the control-plane hosts did not contact the bootstrap-host for their configuration."  Is the bootstap-host the main master? ( i only see 4 virtual machines ) or are you talking about where i am running the openshift-installer from ( my laptop ) 

Here is a log from the serial port on master1
[serial_master1.log](https://github.com/openshift/installer/files/3632467/serial_master1.log)

**Comment by abhinavdahiya** [comment] 2019-09-19 17:34
> Sorry but what did you mean by this?
> 
> "no requests, that means the control-plane hosts did not contact the bootstrap-host for their configuration." Is the bootstap-host the main master? ( i only see 4 virtual machines ) or are you talking about where i am running the openshift-installer from ( my laptop )
> 
> Here is a log from the serial port on master1
> [serial_master1.log](https://github.com/openshift/installer/files/3632467/serial_master1.log)


you can look at how we boot control-plane machines here https://docs.openshift.com/container-platform/4.1/architecture/architecture-installation.html section `Installation process details`

The linked serial logs are from the bootstrap-host (hostname <identifier-b>), the control plane machines are named `<identifier>-m-$idx`

**Comment by pfischer8989** [comment] 2019-09-19 17:34
This is the master1 servers logs as well. 

[core@logan-96ncl-b ~]$ journalctl -b -f -u bootkube.service
-- Logs begin at Thu 2019-09-19 17:07:25 UTC. --
Sep 19 17:19:56 logan-96ncl-b.c.e-ocp4.internal podman[7667]: 2019-09-19 17:19:56.845688074 +0000 UTC m=+0.321085514 container attach 339518391c9e0a1e6ec73c4c294280ee1bbccc992896311592197a5a9da34c8b (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4d0de626756b162300aae1380f25908fdc5bbf4c1ac9b13df02e46d446fe59b3, name=etcdctl)
Sep 19 17:29:56 logan-96ncl-b.c.e-ocp4.internal bootkube.sh[1732]: https://etcd-2.logan.arctiq-ocp4-demo.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-2.logan.arctiq-ocp4-demo.com on 169.254.169.254:53: no such host
Sep 19 17:29:56 logan-96ncl-b.c.e-ocp4.internal bootkube.sh[1732]: https://etcd-0.logan.arctiq-ocp4-demo.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-0.logan.arctiq-ocp4-demo.com on 169.254.169.254:53: no such host
Sep 19 17:29:56 logan-96ncl-b.c.e-ocp4.internal bootkube.sh[1732]: https://etcd-1.logan.arctiq-ocp4-demo.com:2379 is unhealthy: failed to connect: dial tcp: lookup etcd-1.logan.arctiq-ocp4-demo.com on 169.254.169.254:53: no such host
Sep 19 17:29:56 logan-96ncl-b.c.e-ocp4.internal bootkube.sh[1732]: Error: unhealthy cluster
Sep 19 17:29:57 logan-96ncl-b.c.e-ocp4.internal bootkube.sh[1732]: etcdctl failed. Retrying in 5 seconds...
Sep 19 17:30:02 logan-96ncl-b.c.e-ocp4.internal podman[10463]: 2019-09-19 17:30:02.324791636 +0000 UTC m=+0.161619803 container create ceac7bc142f9d42a7906747b87a4d1cd4e71dc8c852fe8f8ce383f75a7d86a14 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4d0de626756b162300aae1380f25908fdc5bbf4c1ac9b13df02e46d446fe59b3, name=etcdctl)
Sep 19 17:30:02 logan-96ncl-b.c.e-ocp4.internal podman[10463]: 2019-09-19 17:30:02.485628556 +0000 UTC m=+0.322456734 container init ceac7bc142f9d42a7906747b87a4d1cd4e71dc8c852fe8f8ce383f75a7d86a14 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4d0de626756b162300aae1380f25908fdc5bbf4c1ac9b13df02e46d446fe59b3, name=etcdctl)
Sep 19 17:30:02 logan-96ncl-b.c.e-ocp4.internal podman[10463]: 2019-09-19 17:30:02.501075649 +0000 UTC m=+0.337903811 container start ceac7bc142f9d42a7906747b87a4d1cd4e71dc8c852fe8f8ce383f75a7d86a14 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4d0de626756b162300aae1380f25908fdc5bbf4c1ac9b13df02e46d446fe59b3, name=etcdctl)
Sep 19 17:30:02 logan-96ncl-b.c.e-ocp4.internal podman[10463]: 2019-09-19 17:30:02.501183894 +0000 UTC m=+0.338012276 container attach ceac7bc142f9d42a7906747b87a4d1cd4e71dc8c852fe8f8ce383f75a7d86a14 (image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4d0de626756b162300aae1380f25908fdc5bbf4c1ac9b13df02e46d446fe59b3, name=etcdctl)
^C
[core@logan-96ncl-b ~]$ journalctl -b -f
-- Logs begin at Thu 2019-09-19 17:07:25 UTC. --
Sep 19 17:33:04 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:04.542653    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:04 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:04.542666    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:08 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:08 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:13 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:13 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:14 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:14.557399    3636 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 19 17:33:14 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:14.563077    3636 kubelet_node_status.go:468] Recording NodeHasSufficientMemory event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:14 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:14.563189    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:14 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:14.563204    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:18 logan-96ncl-b.c.e-ocp4.internal approve-csr.sh[1733]: error: the server doesn't have a resource type "csr"
Sep 19 17:33:18 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:18 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:19 logan-96ncl-b.c.e-ocp4.internal bash[1434]: Processing route for NIC 0/42:01:0a:00:00:02 as ens4 for 34.67.47.152
Sep 19 17:33:23 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:23 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:24 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:24.576380    3636 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 19 17:33:24 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:24.582182    3636 kubelet_node_status.go:468] Recording NodeHasSufficientMemory event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:24 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:24.582226    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:24 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:24.582239    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:28 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:28 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:33 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:33 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:34 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:34.595130    3636 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 19 17:33:34 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:34.600032    3636 kubelet_node_status.go:468] Recording NodeHasSufficientMemory event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:34 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:34.600068    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:34 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:34.600076    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:38 logan-96ncl-b.c.e-ocp4.internal approve-csr.sh[1733]: error: the server doesn't have a resource type "csr"
Sep 19 17:33:39 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:39 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:44 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:44 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:44 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:44.613115    3636 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 19 17:33:44 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:44.618165    3636 kubelet_node_status.go:468] Recording NodeHasSufficientMemory event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:44 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:44.618212    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:44 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:44.618226    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:49 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:49 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:49 logan-96ncl-b.c.e-ocp4.internal bash[1434]: Processing route for NIC 0/42:01:0a:00:00:02 as ens4 for 34.67.47.152
Sep 19 17:33:54 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:54 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:33:54 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:54.628980    3636 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 19 17:33:54 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:54.633802    3636 kubelet_node_status.go:468] Recording NodeHasSufficientMemory event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:54 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:54.633850    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:54 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:54.633866    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:58 logan-96ncl-b.c.e-ocp4.internal approve-csr.sh[1733]: error: the server doesn't have a resource type "csr"
Sep 19 17:33:58 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:58.377504    3636 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 19 17:33:58 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:58.379677    3636 kubelet_node_status.go:468] Recording NodeHasSufficientMemory event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:58 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:58.379721    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:58 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:33:58.379735    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:33:59 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:33:59 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:34:04 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: error: unable to recognize "./99_cloud-creds-secret.yaml": no matches for kind "Secret" in version "v1"
Sep 19 17:34:04 logan-96ncl-b.c.e-ocp4.internal openshift.sh[1734]: kubectl create --filename ./99_cloud-creds-secret.yaml failed. Retrying in 5 seconds...
Sep 19 17:34:04 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:34:04.644692    3636 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
Sep 19 17:34:04 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:34:04.650361    3636 kubelet_node_status.go:468] Recording NodeHasSufficientMemory event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:34:04 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:34:04.650406    3636 kubelet_node_status.go:468] Recording NodeHasNoDiskPressure event message for node logan-96ncl-b.c.e-ocp4.internal
Sep 19 17:34:04 logan-96ncl-b.c.e-ocp4.internal hyperkube[3636]: I0919 17:34:04.650414    3636 kubelet_node_status.go:468] Recording NodeHasSufficientPID event message for node logan-96ncl-b.c.e-ocp4.internal
^C
[core@logan-96ncl-b ~]$

**Comment by pfischer8989** [comment] 2019-09-19 17:36
Ah ok got it....so the bootstrap host is what the logs above are from. Will have a look at the serial logs for the control plane

**Comment by pfischer8989** [comment] 2019-09-19 17:44
ok so this is all DNS again. have a look at the log. Cannot find host when it queries the private domain from the google servers. This is the same issue with the bootstrap host not finding etcd. the machines all have the proper DNS entries in resolv.conf

Is there something i am missing with the DNS config in GCP? i created the root domain and the sa running the installer is owner and has fill permissions to the DNS. It creates the private zone properly and puts the right network there but if i go onto a machine on that network and query the private domain it does not work. What am i missing???? 

[serial_cp.log](https://github.com/openshift/installer/files/3632538/serial_cp.log)

**Comment by abhinavdahiya** [comment] 2019-09-19 17:59
there are some docs from GCP that can can try?
https://cloud.google.com/dns/docs/troubleshooting#private_zones_are_not_resolving_in_the_same_vpc_network

**Comment by pfischer8989** [comment] 2019-09-19 18:29
I was afraid you were going to say that =o)

I ran through all those steps all morning. It all returns as expected but anything inside the private zone will not return. Like if i look up an A record on one of the etcd entries. 

Having said that the last time i ran it it actually worked and resolved but failed in another place. No idea why it worked that time and not the other 15. 

Is there anything special you need to do with the root domain?? I read about sub-delegating as well and out entries in for the nameservers of the private domain as well.....did not seem to do anything. I am at a loss.

**Comment by skandragon** [comment] 2019-10-14 13:22
The problem I have is identical to this.  I believe the issue is that the domain where the record is (the one that was created for this install) is marked as private, and only the install-created networks have access to it.  Thus, on the host I'm running the installer from, it gets a placeholder IP address that is useless.

**Comment by skandragon** [comment] 2019-10-14 13:35
Here's what I did to make it move forward:

**Comment by pfischer8989** [comment] 2019-10-15 01:59
Interesting. I got around this by destroying the project completely and recreating the DNS manually. I had used Terraform on the one that did not work which may have not set up access correctly. 

Once I created a new project and DNS everything worked like a charm.

**Comment by skandragon** [comment] 2019-10-15 04:50
> Once I created a new project and DNS everything worked like a charm.

How did you work around the host where the installer runs not having permissions to talk to the newly created instances?

**Comment by pfischer8989** [comment] 2019-10-15 15:39
I never had authentication issues between the installer vm and the control plane hosts. The ssh key auth always worked. It was just the control plane hosts were not able to resolve the internal zone that the OCP installer created. If that was specific DNS permissions they were resolved when i destroyed the project and rebuilt the DNS, SA, and API permissions

**Comment by skandragon** [comment] 2019-10-16 06:12
Ack.

I feel the issues I had were these, with a bit more detail:

(1) . the "install host" is the instance I am using to run the installer on.
(2) . The "default network" is the VPC network that the installer host is in.

My problems, and how I worked around them:

At one point, the installer attempts to reach out to the newly created cluster (which is in its own VPC), and cannot resolve DNS because the DNS zone created is private, and the default VPC does not have access to it.

Once DNS is resolved, TCP will time out because (for the same reasons) TCP connections between the default and newly created VPC are not permitted.

The fix in the first case was to allow the private DNS zone to be queried (I added this manually).

The fix for the second was to add a peering between the two VPCs, allowing them to communicate.

I am not sure if the installer should handle these issues explicitly, but it feels like it should even if it then removes the added DNS permissions, and removes the peering once install completes.

**Comment by abhinavdahiya** [comment] 2019-10-18 16:37
> cannot resolve DNS because the DNS zone created is private, and the default VPC does not have access to it.

The installer create a DNS Zone (private) in the VPC, but also uses a DNS Zone (public) which is used to create public (accessible to the installer and users outside the VPC) records.

some more detail around that in https://github.com/openshift/installer/blob/master/docs/user/gcp/dns.md

also since the original issue was fixed, i am closing this.

/close

> The fix for the second was to add a peering between the two VPCs, allowing them to communicate.
> I am not sure if the installer should handle these issues explicitly, but it feels like it should even if it then removes the added DNS permissions, and removes the peering once install completes.

And as for creating private OpenShift clusters, there is on going work to support it, but that requires user to run the installer from an environment that has access to pre-existing VPC. The peering connections are almost always user controlled and we have no plans to support that automation.

**Closed by abhinavdahiya** 2019-10-18 16:37 UTC

**Comment by skandragon** [comment] 2019-10-18 19:00
Wait, was the original issue fixed?  What was the commit that fixed it?

**Comment by skandragon** [comment] 2019-10-18 19:05
@abhinavdahiya When you say the original issue was fixed, I am not seeing any commits that relate to this fix.  I also think you misunderstand my work-around, and why it was necessary.

Out of the box, the installer is purely broken on gcp, and I am not sure how your responses about a private cluster, or about the way it creates DNS zones is an accurate description of what it is doing.

**Comment by kyarovoy** [comment] 2020-02-12 10:22
@skandragon - I agree with you, I had the same issue. In a topology when you are deploying private cluster in a custom VPC and your installer host is located in default VPC, at some point during "openshift-install create cluster" it will fail to query dynamically created private DNS zone in a custom VPC since that DNS zone is not configured to be visible for "default" network. 

DNS zone visibility config is defined here:
- https://github.com/openshift/installer/blob/master/data/data/gcp/dns/base.tf

A simple solution would be to change that terraform file, pass gcp_project_id as a variable to DNS module and modify dns zone visibility config to:

```
...
private_visibility_config {
    networks {
      network_url = "https://www.googleapis.com/compute/v1/projects/${var.gcp_project_id}/global/networks/default"
    }
    networks {
      network_url = var.network
    }
  }
...
```
