### ISSUE TITLE
Drop ClusterID from InstallConfig

### ISSUE THREAD

**Issue by dgoodwin** [openshift/installer#761] opened 2018-11-29 17:23 UTC
As discussed in arch call today and at Clayton's request, we decided we should remove the ClusterID from the InstallConfig. It should not be possible for a user to override this value and it should be generated fresh on every installer invocation.

**Comment by crawford** [comment] 2019-01-04 23:46
Duplicate of #538.

**Closed by crawford** 2019-01-04 23:46 UTC
