### ISSUE TITLE
VMware UPI installer if failing using terraform ver 0.12

### ISSUE THREAD

**Issue by mkelnermishal** [openshift/installer#2650] opened 2019-11-11 12:34 UTC
When running terraform init to this installer, using terraform 0.12, the command fails immediately, this looks like incompatibility issue with 0.12. version. It does work with terraform 0.11, but this version will soon be deprecated.

# Version

```console
$ openshift-install version
openshift-install v4.2.0
built from commit 90ccb37ac1f85ae811c50a29f9bb7e779c5045fb
release image quay.io/openshift-release-dev/ocp-release@sha256:c5337afd85b94c93ec513f21c8545e3f9e36a227f55d41bc1dfb8fcc3f2be129
```

# Platform:

UPI on Vmware

# What happened?
Using installer master branch, when running the terraform part in order to deploy the VMs for the OCP cluster, it fails immediately, with the following error:
terraform init
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid argument name

  on machine/main.tf line 47, in resource "vsphere_virtual_machine" "vm":
  47:       "guestinfo.ignition.config.data"          = "${base64encode(data.ignition_config.ign.*.rendered[count.index])}"

# What you expected to happen?

All plugins for providers should have been initialized and the following text would appear:
Terraform has been successfully initialized!

# How to reproduce it (as minimally and precisely as possible)?

Download terraform bin, any 0.12.X version from here:https://www.terraform.io/downloads.html
unzip the zip file and copy terraform bin file to /usr/local/bin
Clone installer repository, edit the details in terraform.tfvars (adding VC, domain, etc.)
run terraform init

# Anything else we need to know?

This is working as expected with terraform 0.11.12. any version above 0.11.14 is breaking. 
Version 0.11 will soon be depracated and I think this code should be changed accordingly, maybe use the conversion script that terraform indicate here: https://www.terraform.io/docs/commands/0.12upgrade.html

**Comment by abhinavdahiya** [comment] 2019-11-11 13:40
Duplicate of https://github.com/openshift/installer/issues/2183

**Closed** 2019-11-11 13:40 UTC
