### ISSUE TITLE
FATAL failed to initialize the cluster: timed out waiting for the condition 

### ISSUE THREAD

**Issue by bbalakriz** [openshift/installer#1309] opened 2019-02-25 08:45 UTC
# Version

```console
$ bin/openshift-install version
bin/openshift-install v0.12.0-dirty
```

# Platform (aws|libvirt|openstack):
libvirt

# What happened?

Installation failed with the error

```
time="2019-02-25T04:29:44Z" level=debug msg="libvirt_domain.bootstrap: Refreshing state... (ID: aeee6d4a-74db-4de0-a4de-f14f5796e6af)"
time="2019-02-25T04:29:44Z" level=debug msg="module.bootstrap.libvirt_domain.bootstrap: Destroying... (ID: aeee6d4a-74db-4de0-a4de-f14f5796e6af)"
time="2019-02-25T04:29:45Z" level=debug msg="module.bootstrap.libvirt_domain.bootstrap: Destruction complete after 1s"
time="2019-02-25T04:29:45Z" level=debug msg="module.bootstrap.libvirt_ignition.bootstrap: Destroying... (ID: /var/lib/libvirt/images/test1-bootstrap.ign;5c736c4b-b511-a506-19fa-b8ee381b37df)"
time="2019-02-25T04:29:45Z" level=debug msg="module.bootstrap.libvirt_volume.bootstrap: Destroying... (ID: /var/lib/libvirt/images/test1-bootstrap)"
time="2019-02-25T04:29:45Z" level=debug msg="module.bootstrap.libvirt_ignition.bootstrap: Destruction complete after 0s"
time="2019-02-25T04:29:45Z" level=debug msg="module.bootstrap.libvirt_volume.bootstrap: Destruction complete after 0s"
time="2019-02-25T04:29:45Z" level=debug
time="2019-02-25T04:29:45Z" level=debug msg="Destroy complete! Resources: 3 destroyed."
time="2019-02-25T04:29:45Z" level=info msg="Waiting up to 30m0s for the cluster to initialize..."
time="2019-02-25T04:29:45Z" level=debug msg="Still waiting for the cluster to initialize..."
time="2019-02-25T04:31:10Z" level=debug msg="Still waiting for the cluster to initialize: Could not update clusteroperator \"openshift-apiserver\" (config.openshift.io/v1, 115 of 241)"
time="2019-02-25T04:33:10Z" level=debug msg="Still waiting for the cluster to initialize..."
time="2019-02-25T04:34:25Z" level=debug msg="Still waiting for the cluster to initialize: Could not update clusteroperator \"cluster-monitoring-operator\" (config.openshift.io/v1, 176 of 241): resource may have been deleted"
time="2019-02-25T04:59:45Z" level=fatal msg="failed to initialize the cluster: timed out waiting for the condition" 
```

# What you expected to happen?

Installation should have succeeded.

# How to reproduce it (as minimally and precisely as possible)?

This is consistently reproducible by following the steps given in the instructions given in [libvirt-howto.md](https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md) 

```console
apiVersion: v1beta2
baseDomain: tt.testing
machines:
- name: master
  platform: {}
  replicas: 1
- name: worker
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: test1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 192.168.126.0/24
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
pullSecret: <snip>
sshKey: |
  ssh-rsa <snip>
```

# Anything else we need to know?

Debian GNU/Linux 9.7 (stretch)
openshift_install.log - https://gist.github.com/bbalakriz/189fb7fa708aefc2566479d3983abac0#file-openshift_install-log

**Comment by zeenix** [comment] 2019-06-17 15:01
Duplicate of #1428 i think.

/label triage/duplicate

/close

**Closed by zeenix** 2019-06-17 15:01 UTC
Labels: platform/libvirt
