### ISSUE TITLE
[libvirt] Problem with openshift-console <POD>

### ISSUE THREAD

**Issue by ssbano** [openshift/installer#1397] opened 2019-03-09 13:04 UTC
# Version

```console
$ openshift-install version
./openshift-install unreleased-master-540-g12af0c9b8e6a090c041b19c2fb0c040188607bcb-dirty
```

# Platform (aws|libvirt|openstack):

Libvirt

# What happened?

[fsbano@voyager-1 ~]$ oc logs console-78444cb4bb-m2cmw
2019/03/9 12:54:58 cmd/main: cookies are secure!
2019/03/9 12:54:58 auth: error contacting auth provider (retrying in 2s): request to OAuth issuer endpoint https://openshift-authentication-openshift-authentication.apps.jaguar.fsbano.io/oauth/token failed: Head https://openshift-authentication-openshift-authentication.apps.jaguar.fsbano.io: dial tcp: lookup openshift-authentication-openshift-authentication.apps.jaguar.fsbano.io on 172.30.0.10:53: no such host

"no such host" 

# What you expected to happen?

*.apps.${CLUSTER_NAME}.${BASE_DOMAIN}

# How to reproduce it (as minimally and precisely as possible)?

```console
$ ./openshift-install create cluster
```

# Anything else we need to know?

I solved the problem by creating a zone "apps.${CLUSTER_NAME}.${BASE_DOMAIN}" inside bind

# References
#1382
#1078

**Comment by anildhingra** [comment] 2019-03-10 06:30
possible to share bind config or what need to be done for Networkmanager dnsmasq  as per libvirt doc 
or are you using separate DNS server on physical machine

it will help to request modify libvirt doc as a saw most of users stuck here

**Comment by ssbano** [comment] 2019-03-10 07:21
> possible to share bind config or what need to be done for Networkmanager dnsmasq as per libvirt doc
> or are you using separate DNS server on physical machine
> 
> it will help to request modify libvirt doc as a saw most of users stuck here

Hi, Anil Dhingra
I'll be sharing soon I'm adjusting some things in the installer too.

Best Regards,
Fabio Sbano

**Comment by ssbano** [comment] 2019-03-10 07:52
Hi, Anil Dhringra

Please see this topic (#1078) a few days ago I put the step-by-step

Will you let me do a PR?

Best regards,
Fabio Sbano

**Comment by anildhingra** [comment] 2019-03-10 11:39
so you are not using NetworkManager like libvirt doc 

/etc/NetworkManager/conf.d/openshift.conf
 /etc/NetworkManager/dnsmasq.d/openshift.conf

so i can remove config from above & configure a dns server on physical host ?

**Comment by ssbano** [comment] 2019-03-10 11:52
Hi, Anil Dhringra

During the installation process you can use dnsmasq and at the end when the console is pending you start your bind (physical host) by listening on the 192.168.126.1 ip

Ex: 
zone "test1.tt.testing"
zone "apps.test1.tt.testing"

Best Regards,
Fábio Sbano

**Comment by ssbano** [comment] 2019-03-10 12:23
Hi,

My Setup

[root@voyager-1 ~]# cat /etc/NetworkManager/conf.d/openshift.conf
```
[main]
dns=dnsmasq
[root@voyager-1 ~]# 
```

[root@voyager-1 ~]# cat /etc/NetworkManager/dnsmasq.d/openshift.conf
```
server=/fsbano.io/192.168.126.1
[root@voyager-1 ~]# 
```

[root@voyager-1 ~]# cat /etc/resolv.conf
```
search fsbano.io
nameserver 127.0.0.1
[root@voyager-1 ~]# 
```

[root@voyager-1 ~]# cat /etc/named.conf 
```
//
// named.conf
//
// Provided by Red Hat bind package to configure the ISC BIND named(8) DNS
// server as a caching only nameserver (as a localhost DNS resolver only).
//
// See /usr/share/doc/bind*/sample/ for example named configuration files.
//

options {
	listen-on port 53 { 192.168.126.1; };
	listen-on-v6 port 53 { ::1; };
	directory 	"/var/named";
	dump-file 	"/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	secroots-file	"/var/named/data/named.secroots";
	recursing-file	"/var/named/data/named.recursing";
	allow-query     { any; };

	/* 
	 - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
	 - If you are building a RECURSIVE (caching) DNS server, you need to enable 
	   recursion. 
	 - If your recursive DNS server has a public IP address, you MUST enable access 
	   control to limit queries to your legitimate users. Failing to do so will
	   cause your server to become part of large scale DNS amplification 
	   attacks. Implementing BCP38 within your network would greatly
	   reduce such attack surface 
	*/
	recursion yes;

	dnssec-enable yes;
	dnssec-validation yes;

	managed-keys-directory "/var/named/dynamic";

	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";

	/* https://fedoraproject.org/wiki/Changes/CryptoPolicy */
	include "/etc/crypto-policies/back-ends/bind.config";

        forwarders { 8.8.8.8; };
};

logging {
        channel default_debug {
                file "data/named.run";
                severity dynamic;
        };
};

zone "." IN {
	type hint;
	file "named.ca";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";

[root@voyager-1 ~]# 
[root@voyager-1 ~]# cat /etc/named.conf 
//
// named.conf
//
// Provided by Red Hat bind package to configure the ISC BIND named(8) DNS
// server as a caching only nameserver (as a localhost DNS resolver only).
//
// See /usr/share/doc/bind*/sample/ for example named configuration files.
//

options {
	listen-on port 53 { 192.168.126.1; };
	listen-on-v6 port 53 { ::1; };
	directory 	"/var/named";
	dump-file 	"/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	secroots-file	"/var/named/data/named.secroots";
	recursing-file	"/var/named/data/named.recursing";
	allow-query     { any; };

	/* 
	 - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
	 - If you are building a RECURSIVE (caching) DNS server, you need to enable 
	   recursion. 
	 - If your recursive DNS server has a public IP address, you MUST enable access 
	   control to limit queries to your legitimate users. Failing to do so will
	   cause your server to become part of large scale DNS amplification 
	   attacks. Implementing BCP38 within your network would greatly
	   reduce such attack surface 
	*/
	recursion yes;

	dnssec-enable yes;
	dnssec-validation yes;

	managed-keys-directory "/var/named/dynamic";

	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";

	/* https://fedoraproject.org/wiki/Changes/CryptoPolicy */
	include "/etc/crypto-policies/back-ends/bind.config";

        forwarders { 8.8.8.8; };
};

logging {
        channel default_debug {
                file "data/named.run";
                severity dynamic;
        };
};

zone "." IN {
	type hint;
	file "named.ca";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
```

[root@voyager-1 ~]# cat /var/named/named.jaguar.fsbano.io 
```
$TTL 0
@	IN SOA	@ rname.invalid. (
					0	; serial
					1D	; refresh
					1H	; retry
					1W	; expire
					3H )	; minimum
	  NS	@
	  A	192.168.126.1
api       A     192.168.126.11
etcd-0    A     192.168.126.11
jaguar-6w5x9-master-0 CNAME api
jaguar-6w5x9-worker-0-2p7qp A 192.168.126.51
jaguar-6w5x9-worker-0-c6prk A 192.168.126.52
```

[root@voyager-1 ~]# cat /var/named/named.apps.jaguar.fsbano.io 
```
$TTL 0
@	IN SOA	@ rname.invalid. (
					0	; serial
					1D	; refresh
					1H	; retry
					1W	; expire
					3H )	; minimum
	  NS	@
	  A	192.168.126.1
*         A     192.168.126.51
*         A     192.168.126.52
[root@voyager-1 ~]# 
```

Regards,
Fábio Sbano

**Comment by ssbano** [comment] 2019-03-10 19:34
Hi,
Sorry, I forgot something

<forwarder domain='apps.jaguar.fsbano.io' addr='192.168.x.x'/>

[root@voyager-1 ~]# virsh net-dumpxml jaguar-jfcpr
```
<network connections='3'>
  <name>jaguar-jfcpr</name>
  <uuid>1684a349-8686-4198-854c-5d0f8209ec7b</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='tt0' stp='on' delay='0'/>
  <mac address='52:54:00:71:5f:d0'/>
  <domain name='jaguar.fsbano.io' localOnly='yes'/>
  <dns>
    **<forwarder domain='apps.jaguar.fsbano.io' addr='192.168.1.1'/>**
    <srv service='etcd-server-ssl' protocol='tcp' domain='jaguar.fsbano.io' target='etcd-0.jaguar.fsbano.io' port='2380' weight='10'/>
    <host ip='192.168.126.11'>
      <hostname>api.jaguar.fsbano.io</hostname>
      <hostname>etcd-0.jaguar.fsbano.io</hostname>
    </host>
  </dns>
  <ip family='ipv4' address='192.168.126.1' prefix='24'>
    <dhcp>
      <host mac='66:4f:16:3f:5f:0f' name='jaguar-jfcpr-master-0' ip='192.168.126.11'/>
      <host mac='0e:cb:ab:5e:3b:3a' name='jaguar-jfcpr-worker-0-pldrn' ip='192.168.126.51'/>
      <host mac='46:6a:2c:3d:fd:51' name='jaguar-jfcpr-worker-0-fhhdr' ip='192.168.126.52'/>
    </dhcp>
  </ip>
</network>

[root@voyager-1 ~]# 
```
Good Night,
Fabio Sbano

**Comment by ssbano** [comment] 2019-03-10 19:45
Hi,

You need to configure 'mac' - 'hostname' - 'ip' for DHCP to _assign virtual machines_ when restarting your **physical host**

```
  <ip family='ipv4' address='192.168.126.1' prefix='24'>
    <dhcp>
      <host mac='66:4f:16:3f:5f:0f' name='jaguar-jfcpr-master-0' ip='192.168.126.11'/>
      <host mac='0e:cb:ab:5e:3b:3a' name='jaguar-jfcpr-worker-0-pldrn' ip='192.168.126.51'/>
      <host mac='46:6a:2c:3d:fd:51' name='jaguar-jfcpr-worker-0-fhhdr' ip='192.168.126.52'/>
    </dhcp>
  </ip>
```

**Comment by praveenkumar** [comment] 2019-03-11 10:28
I put a PR sometime back to solve it with using a different route and add that entry to dnsmasq. @ssbano @anildhingra can you have a look and see if that works for you? 

https://github.com/openshift/installer/pull/1371

**Comment by ssbano** [comment] 2019-03-11 10:58
Hi,

I had not seen that note.

Is running the wildcard with subdomain the name resolutions?

Best Regards,
Fábio Sbano

**Comment by praveenkumar** [comment] 2019-03-11 12:09
> Is running the wildcard with subdomain the name resolutions?

Yes, you can try that and also make a subdomain query in the VM which should successful.

**Comment by ssbano** [comment] 2019-03-11 12:34
@praveenkumar,

very good I had to solve this problem by creating an external zone in bind and pointing inside the configuration of libvirt-net to make forwarder.

it's much simpler
I'll try tonight and give you a reply.

Regards,
Fábio Sbano

**Comment by ssbano** [comment] 2019-03-13 09:09
Workaround #1371

**Comment by Sarang-Sangram** [comment] 2019-08-12 04:44
> Hi,
> Sorry, I forgot something
> 
> ```
> <forwarder domain='apps.jaguar.fsbano.io' addr='192.168.x.x'/>
> ```
> 
> my settings below
> 
> [root@voyager-1 ~]# virsh net-dumpxml jaguar-jfcpr
> 
> ```
> <network connections='3'>
>   <name>jaguar-jfcpr</name>
>   <uuid>1684a349-8686-4198-854c-5d0f8209ec7b</uuid>
>   <forward mode='nat'>
>     <nat>
>       <port start='1024' end='65535'/>
>     </nat>
>   </forward>
>   <bridge name='tt0' stp='on' delay='0'/>
>   <mac address='52:54:00:71:5f:d0'/>
>   <domain name='jaguar.fsbano.io' localOnly='yes'/>
>   <dns>
>     <forwarder domain='apps.jaguar.fsbano.io' addr='192.168.1.1'/>
>     <srv service='etcd-server-ssl' protocol='tcp' domain='jaguar.fsbano.io' target='etcd-0.jaguar.fsbano.io' port='2380' weight='10'/>
>     <host ip='192.168.126.11'>
>       <hostname>api.jaguar.fsbano.io</hostname>
>       <hostname>etcd-0.jaguar.fsbano.io</hostname>
>     </host>
>   </dns>
>   <ip family='ipv4' address='192.168.126.1' prefix='24'>
>     <dhcp>
>       <host mac='66:4f:16:3f:5f:0f' name='jaguar-jfcpr-master-0' ip='192.168.126.11'/>
>       <host mac='0e:cb:ab:5e:3b:3a' name='jaguar-jfcpr-worker-0-pldrn' ip='192.168.126.51'/>
>       <host mac='46:6a:2c:3d:fd:51' name='jaguar-jfcpr-worker-0-fhhdr' ip='192.168.126.52'/>
>     </dhcp>
>   </ip>
> </network>
> 
> [root@voyager-1 ~]# 
> ```
> 
> Good Night,
> Fabio Sbano
@ssbano How are you adding this piece in the xml file ? 
`<forwarder domain='apps.jaguar.fsbano.io' addr='192.168.x.x'/>`

**Comment by ssbano** [comment] 2019-09-25 11:33
@sa

**Comment by ssbano** [comment] 2019-09-25 11:35
@sarang-sangram,

I am using bind instead of dnsmasq

Regards,
Fabio Sbano

**Comment by ssbano** [comment] 2019-09-28 07:19
@Sarang-Sangram 

https://pbs.twimg.com/media/EFiKJ0OW4AAc4xn?format=png&name=large

Regards,
Fabio Sbano

**Comment by zeenix** [comment] 2019-10-08 13:51
@ssbano Isn't this a duplicate of https://github.com/openshift/installer/issues/1007 ?

**Comment by ssbano** [comment] 2019-10-08 14:09
@zeenix,

Yes, i can closed .. do you prefer?

*dnsmasq not running for me to wildcard. I need migrate to the bind 

Best Regards,
Fabio Sbano

**Comment by abhinavdahiya** [comment] 2019-11-05 17:31
duplicate of https://github.com/openshift/installer/issues/1007

/close

**Closed by abhinavdahiya** 2019-11-05 17:31 UTC
