### ISSUE TITLE
Browsing to console before DNS is ready causes console to *always* say IP not found

### ISSUE THREAD

**Issue by wgordon17** [openshift/installer#974] opened 2018-12-30 04:54 UTC
# Version

MacOS 10.14.2
Chrome Version 71.0.3578.98
Firefox 64.0
./openshift-install v0.8.0

# Platform (aws|libvirt|openstack): aws

# What happened?

Visiting the console URL immediately after it's displayed in the CLI output causes both Chrome and Firefox browsers to display no IP found for URL. After waiting several minutes, other URLs work, but the console URL never fixes itself

# What you expected to happen?

Console to work

# Anything else we need to know?

I'm guessing this is some kind of weird URL cache

**Comment by wgordon17** [comment] 2018-12-30 15:20
This is likely a DNS propagation issue, however it would be ideal if the installer could at least test local DNS for when it resolves before showing the install as "complete" and making the console URL immediately available. Especially since this seems to cause some weird DNS caching issue (at least on Mac), where even though other *.apps.<cluster>.<base-domain> URLs work, the console still refuses to work.

Additionally, if it's possible, maybe set the DNS settings in AWS as soon as possible to provide the maximum amount of time to propagate.

**Comment by wking** [comment] 2019-01-02 21:42
> ... however it would be ideal if the installer could at least test local DNS for when it resolves before showing the install as "complete" and making the console URL immediately available.

See [here][1] about a currently-missing wait for `login` support.  That seems orthogonal to DNS issue. Can you use your browser's network logs to see how DNS is resolving?  It would be interesting to see what it gets before the route is configured and how it gets stuck even after the route is configured.

We could wait until the install host was able to resolve the console DNS host.  That would slow down apparent installation for folks who don't need the console, but since #771 we've been [slanting towards console users][2] anyway.  Thoughts, @abhinavdahiya, @crawford?

> Additionally, if it's possible, maybe set the DNS settings in AWS as soon as possible to provide the maximum amount of time to propagate.

The `*.apps.{cluster}.{base-domain}` entry is created by an operator ([ingress][3]?), so the installer doesn't have direct control over when it is set up.

[1]: https://github.com/openshift/installer/pull/806#issuecomment-444990344
[2]: https://github.com/openshift/installer/pull/771#issuecomment-444332926
[3]: https://github.com/openshift/cluster-ingress-operator

**Comment by wgordon17** [comment] 2019-01-02 22:40
Unfortunately, there are no browser network logs (at least not in Chrome). It just attempts to resolve it, then immediately throws me to a "Site can't be found" (or whatever) error message.

The issue that I think is preventing access even after the console is created is that the browsers are too aggressively caching the `no DNS` problem, and it definitely persists even after any other `*.apps.{cluster}.{base-domain}` URL works.

I think adding a DNS check on `*.apps.{cluster}.{base-domain}` would be beneficial, and would likely only add another minute or two at the most to installation time. Just being as verbose as possible ("Waiting for DNS to propagate...") would be helpful in terms of the perceived slowness.

**Comment by wking** [comment] 2019-01-02 23:01
> Unfortunately, there are no browser network logs (at least not in Chrome).

Notes for DNS logging in Firefox are [here][1].  For me, resolving does-not-exist.example.com generates logs like:

```console
$ grep D/nsHostResolver /tmp/log.txt-main.24912 
2019-01-02 22:51:17.688651 UTC - [24912:Main Thread]: D/nsHostResolver Resolving host [does-not-exist.example.com].
2019-01-02 22:51:17.688660 UTC - [24912:Main Thread]: D/nsHostResolver   No usable address in cache for host [does-not-exist.example.com].
2019-01-02 22:51:17.688668 UTC - [24912:Main Thread]: D/nsHostResolver   DNS thread counters: total=2 any-live=0 idle=2 pending=1
2019-01-02 22:51:17.688673 UTC - [24912:Main Thread]: D/nsHostResolver   DNS lookup for host [does-not-exist.example.com] blocking pending 'getaddrinfo' query: callback [0x7f960f5609d0]
2019-01-02 22:51:17.688711 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver DNS lookup thread - Calling getaddrinfo for host [does-not-exist.example.com].
2019-01-02 22:51:17.689775 UTC - [24912:Socket Thread]: D/nsHostResolver Resolving host [does-not-exist.example.com].
2019-01-02 22:51:17.689782 UTC - [24912:Socket Thread]: D/nsHostResolver   Host [does-not-exist.example.com] is being resolved. Appending callback [0x7f960f8b85e0].
2019-01-02 22:51:17.693271 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver Calling 'res_ninit'.
2019-01-02 22:51:17.696361 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver DNS lookup thread - lookup completed for host [does-not-exist.example.com]: failure: unknown host.
2019-01-02 22:51:17.696401 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver nsHostResolver::CompleteLookup does-not-exist.example.com (nil) 804B001E trr=0 stillResolving=0
2019-01-02 22:51:17.696416 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver nsHostResolver record 0x7f96420e2a40 new gencnt
2019-01-02 22:51:17.696431 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver Caching host [does-not-exist.example.com] negative record for 60 seconds.
2019-01-02 22:51:17.696442 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver CompleteLookup: does-not-exist.example.com has NO address
2019-01-02 22:51:17.696454 UTC - [24912:DNS Resolver #1655]: D/nsHostResolver nsHostResolver record 0x7f96420e2a40 calling back dns users
2019-01-02 22:51:17.723207 UTC - [24912:Socket Thread]: D/nsHostResolver Resolving host [does-not-exist.example.com].
2019-01-02 22:51:17.723219 UTC - [24912:Socket Thread]: D/nsHostResolver   No usable address in cache for host [does-not-exist.example.com].
2019-01-02 22:51:17.723229 UTC - [24912:Socket Thread]: D/nsHostResolver   DNS thread counters: total=2 any-live=0 idle=2 pending=1
2019-01-02 22:51:17.723236 UTC - [24912:Socket Thread]: D/nsHostResolver   DNS lookup for host [does-not-exist.example.com] blocking pending 'getaddrinfo' query: callback [0x7f960d723b80]
2019-01-02 22:51:17.723281 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver DNS lookup thread - Calling getaddrinfo for host [does-not-exist.example.com].
2019-01-02 22:51:17.726439 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver Calling 'res_ninit'.
2019-01-02 22:51:17.729090 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver DNS lookup thread - lookup completed for host [does-not-exist.example.com]: failure: unknown host.
2019-01-02 22:51:17.729104 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver nsHostResolver::CompleteLookup does-not-exist.example.com (nil) 804B001E trr=0 stillResolving=0
2019-01-02 22:51:17.729109 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver nsHostResolver record 0x7f96420e2a40 new gencnt
2019-01-02 22:51:17.729113 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver Caching host [does-not-exist.example.com] negative record for 60 seconds.
2019-01-02 22:51:17.729117 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver CompleteLookup: does-not-exist.example.com has NO address
2019-01-02 22:51:17.729121 UTC - [24912:DNS Resolver #1652]: D/nsHostResolver nsHostResolver record 0x7f96420e2a40 calling back dns users
```

[1]: https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging

**Comment by crawford** [comment] 2019-01-03 01:39
The symptoms you are describing sound exactly inline with how DNS is supposed to work. Your resolver and the nameservers in between you and the authoritative server will respect the TTLs listed in the SOA record for your domain. If you want to wait less than 15 minutes (the default for AWS domains), you'll need to update the appropriate TTLs in your SOA (and make sure to bump the serial number to initiate the zone transfer). The downside to a lower TTL, of course, is more frequent name lookups which may result in an overall increase in latency.

Ultimately, I don't think there is anything we can do about this short of leaving a note somewhere in the docs.

**Comment by wking** [comment] 2019-01-03 17:50
> Without the check, user could attempt the URL right away, and potentially prevent themselves from accessing the console for up to 15 minutes!

Wouldn't this depend on the whole DNS chain?  Do we expect the browser's internal cache to be slower to update than the host-level DNS cache?  Or other upstream DNS caches?  Attempting to resolve the domain in the installer would pull the "entry not defined yet" response into host-level and upstream caches, it just cuts out the browser's cache.

> https://gist.github.com/wgordon17/f2e3f1bf3159f4d11fd41b3303576f79

Looks like that failed to resolve the console at 15:50:40, and you successfully resolved test3 at 15:51:41.  Do you see anything about failing to resolve the console after that?  I'd expect something about seeing a cached "entry not defined" if the problem is really the browser cache holding onto the old value.

**Comment by crawford** [comment] 2019-01-05 00:19
> By adding a DNS check (or curling the URL until accessible) should only add another minute or so to the installation process (after several tests, URL was always available within 1.5 minutes).

If the installer performs the DNS lookup, it's going to run into the same 15-minute slowdown you mentioned before. There really isn't a way to ensure that DNS has propagated without triggering the negative caching.

**Comment by wgordon17** [comment] 2019-01-08 16:19
By performing DNS testing on `{uuid}.apps.{cluster}.{base-domain}` you would effectively be testing a new URL everytime and prevent the negative caching (would only cache the changing `uuid` URLs which would unlikely ever by tested by the end user)

**Comment by abhinavdahiya** [comment] 2019-08-09 16:49
I don't think the installer is going to move ahead on performing DNS checks for the console. Those don't provide a whole lot of value.

/close

**Closed by abhinavdahiya** 2019-08-09 16:49 UTC
