### ISSUE TITLE
Set Router service "Private" instead of LoadBalancerService during install

### ISSUE THREAD

**Issue by JuozasA** [openshift/installer#1987] opened 2019-07-15 13:26 UTC
# Version
```console
$ ./openshift-install version
./openshift-install unreleased-master-1258-g1a78ab5e12aa9295b20c789c0e42c0760bb753c1
built from commit 1a78ab5e12aa9295b20c789c0e42c0760bb753c1
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:
Azure

# What happened?
Is there a way to change the cluster-ingress-operator provisioned router service from LoadBalancerService to Private (or ClusterIP) so that it wont create the Loadbalancer on Azure once Openshift is installed?

# What you expected to happen?
either install-config or one of the manifests accept the Endpoint Publishing Strategy parameter and wont create LoadBalancer for router on Azure/AWS. This would be useful if users would like to lock down the Internet access and only allow IPs form particular range defined in Network Security groups.

# How to reproduce it (as minimally and precisely as possible)?
comes by default when installing OCP

**Comment by abhinavdahiya** [comment] 2019-07-15 13:58
Send like a duplicate of https://github.com/openshift/installer/issues/1946

/close

**Closed by abhinavdahiya** 2019-07-15 13:58 UTC
